// extension.js - Generated by Gleam extension_generator
// DO NOT EDIT - Regenerate with: gleam run -m extension_generator

import { Text } from "@mariozechner/pi-tui";
import { notify_error as pi_extension_notify_error, pi_send_message as pi_extension_pi_send_message } from "./build/dev/javascript/psypi/pi_extension.mjs";
import { record_trigger } from "./build/dev/javascript/psypi/event_hooks.mjs";

import { get_resolved_identity as agent_identity_get_resolved_identity } from "./build/dev/javascript/psypi/agent_identity.mjs";
import { add as task_add } from "./build/dev/javascript/psypi/task.mjs";
import { list as task_list } from "./build/dev/javascript/psypi/task.mjs";
import { complete as task_complete } from "./build/dev/javascript/psypi/task.mjs";
import { stats as stats_stats } from "./build/dev/javascript/psypi/stats.mjs";
import { save_version as code_version_save_version } from "./build/dev/javascript/psypi/code_version.mjs";
import { get_versions as code_version_get_versions } from "./build/dev/javascript/psypi/code_version.mjs";
import { add as issue_db_add } from "./build/dev/javascript/psypi/issue_db.mjs";
import { list as issue_db_list } from "./build/dev/javascript/psypi/issue_db.mjs";
import { count as issue_db_count } from "./build/dev/javascript/psypi/issue_db.mjs";
import { get as issue_db_get } from "./build/dev/javascript/psypi/issue_db.mjs";
import { resolve as issue_db_resolve } from "./build/dev/javascript/psypi/issue_db.mjs";
import { list as skill_list } from "./build/dev/javascript/psypi/skill.mjs";
import { get as skill_get } from "./build/dev/javascript/psypi/skill.mjs";
import { search as skill_search } from "./build/dev/javascript/psypi/skill.mjs";
import { list as meeting_list } from "./build/dev/javascript/psypi/meeting.mjs";
import { get as meeting_get } from "./build/dev/javascript/psypi/meeting.mjs";
import { list_opinions as meeting_list_opinions } from "./build/dev/javascript/psypi/meeting.mjs";
import { create as meeting_create } from "./build/dev/javascript/psypi/meeting.mjs";
import { add_opinion as meeting_add_opinion } from "./build/dev/javascript/psypi/meeting.mjs";
import { save as learning_save } from "./build/dev/javascript/psypi/learning.mjs";
import { search as memory_search } from "./build/dev/javascript/psypi/memory.mjs";
import { send as broadcast_send } from "./build/dev/javascript/psypi/broadcast.mjs";
import { list as broadcast_list } from "./build/dev/javascript/psypi/broadcast.mjs";
import { areflect as areflect_areflect } from "./build/dev/javascript/psypi/areflect.mjs";
import { list as agents_list } from "./build/dev/javascript/psypi/agents.mjs";
import { start_monitor_loop as monitor_ai_start_monitor_loop } from "./build/dev/javascript/psypi/monitor_ai.mjs";
import { check_system_health as monitor_ai_check_system_health } from "./build/dev/javascript/psypi/monitor_ai.mjs";
import { get_alerts as monitor_ai_get_alerts } from "./build/dev/javascript/psypi/monitor_ai.mjs";
import { get_model_stats as monitor_ai_get_model_stats } from "./build/dev/javascript/psypi/monitor_ai.mjs";
import { get_work_suggestions as monitor_ai_get_work_suggestions } from "./build/dev/javascript/psypi/monitor_ai.mjs";
import { list_all_hooks as event_hooks_list_all_hooks } from "./build/dev/javascript/psypi/event_hooks.mjs";
import { list_active_hooks as event_hooks_list_active_hooks } from "./build/dev/javascript/psypi/event_hooks.mjs";
import { set_directive as directive_set_directive } from "./build/dev/javascript/psypi/directive.mjs";
import { clear_directives as directive_clear_directives } from "./build/dev/javascript/psypi/directive.mjs";
import { on_consult as tool_consult_on_consult } from "./build/dev/javascript/psypi/tool_consult.mjs";
import { on_commit as tool_commit_on_commit } from "./build/dev/javascript/psypi/tool_commit.mjs";


export default function(pi) {
  function unwrapGleamResult(result) {
    if (!result) return { ok: false, error: 'null result' };
    const typeName = result.constructor?.name || '';
    if (typeName === 'Ok') return { ok: true, value: result['0'] };
    if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };
    return { ok: true, value: result };
  }

  // Register custom renderer for A-agentbot (autonomic) wake-up messages
  pi.registerMessageRenderer('autonomic-wakeup', (message, options, theme) => {
    const { expanded } = options;
    let text = theme.fg('accent', '[A-agentbot] ');
    text += theme.fg('warning', message.content);
    if (expanded && message.details) {
      text += '\n' + theme.fg('dim', JSON.stringify(message.details, null, 2));
    }
    return new Text(text, 0, 0);
  });

  // Event hook: tool_call
  pi.on('tool_call', async (event, ctx) => {
    try {

      const hook_on_tool_call_on_tool_call = (await import('./build/dev/javascript/psypi/hook_on_tool_call.mjs')).on_tool_call;
      const result = await hook_on_tool_call_on_tool_call(event.toolName || '', event.input ? (event.input.path || event.input.filePath || '') : '', ctx, pi);
      const r = unwrapGleamResult(result);
      if (r.ok) {  }
      else { ctx.ui.notify('Hook tool_call failed: ' + r.error, 'error'); pi_extension_pi_send_message(pi, 'hook-error', 'Hook tool_call failed: ' + r.error, 'error'); }
      await record_trigger('tool_call');

    } catch(e) {
      ctx.ui.notify('Hook tool_call error: ' + (e.message || String(e)), 'error');
      pi_extension_pi_send_message(pi, 'hook-error', 'Hook tool_call error: ' + (e.message || String(e)), 'error');

    }
  });

  // Event hook: session_start
  pi.on('session_start', async (event, ctx) => {
    try {
    if (ctx.model) {

      const monitor_record_current_model = (await import('./build/dev/javascript/psypi/monitor.mjs')).record_current_model;
      const result = await monitor_record_current_model(ctx.model);
      const r = unwrapGleamResult(result);
      if (r.ok) {  }
      else { ctx.ui.notify('Hook session_start failed: ' + r.error, 'error'); pi_extension_pi_send_message(pi, 'hook-error', 'Hook session_start failed: ' + r.error, 'error'); }
      await record_trigger('session_start');
    }

    } catch(e) {
      ctx.ui.notify('Hook session_start error: ' + (e.message || String(e)), 'error');
      pi_extension_pi_send_message(pi, 'hook-error', 'Hook session_start error: ' + (e.message || String(e)), 'error');

    }
  });

  // Event hook: model_select
  pi.on('model_select', async (event, ctx) => {
    try {
    if (event.model) {

      const monitor_record_current_model = (await import('./build/dev/javascript/psypi/monitor.mjs')).record_current_model;
      const result = await monitor_record_current_model(event.model);
      const r = unwrapGleamResult(result);
      if (r.ok) {  }
      else { ctx.ui.notify('Hook model_select failed: ' + r.error, 'error'); pi_extension_pi_send_message(pi, 'hook-error', 'Hook model_select failed: ' + r.error, 'error'); }
      await record_trigger('model_select');
    }

    } catch(e) {
      ctx.ui.notify('Hook model_select error: ' + (e.message || String(e)), 'error');
      pi_extension_pi_send_message(pi, 'hook-error', 'Hook model_select error: ' + (e.message || String(e)), 'error');

    }
  });

  // Event hook: before_agent_start
  pi.on('before_agent_start', async (event, ctx) => {
    return { systemPrompt: '\n[A-S Role Model] You are the Somatic Agentbot (S-agentbot). Your ID starts with S-. You are NOT the Autonomic Agentbot (A-agentbot). Messages prefixed with [A-agentbot] come from A — your coordinator. A directs you on what to work on. Follow A\'s instructions as task assignments. The human user is the person operating the terminal.' };

  });

  // Event hook: agent_start
  pi.on('agent_start', async (event, ctx) => {
    // agent_start: S is starting, A stays silent

  });

  // Event hook (debounced): agent_end
  pi.on('agent_end', async (event, ctx) => {
    try {
      // Phase 1: Check if S is actually idle
      const idle = ctx.isIdle();
      ctx.ui.notify('[AUTONOMIC] isIdle=' + idle, 'info');
      if (!idle) { return; }
      const system_config_get_debounce_ms = (await import('./build/dev/javascript/psypi/system_config.mjs')).get_debounce_ms;
      const debounceResult = await system_config_get_debounce_ms();
      const dr = unwrapGleamResult(debounceResult);
      if (!dr.ok) { ctx.ui.notify('Hook agent_end <ERROR> debounce config: ' + dr.error, 'error'); pi_extension_pi_send_message(pi, 'hook-error', 'Hook agent_end <ERROR> debounce config: ' + dr.error, 'error'); return; }
      const debounceMs = dr.value;
      setTimeout(async () => {
        try {
          ctx.ui.notify('[AUTONOMIC] setTimeout callback fired for agent_end', 'info');
          const hook_on_agent_end_on_agent_end = (await import('./build/dev/javascript/psypi/hook_on_agent_end.mjs')).on_agent_end;
          const result = await hook_on_agent_end_on_agent_end(ctx, pi);
          const r = unwrapGleamResult(result);
          if (r.ok) {  }
          else { ctx.ui.notify('Hook agent_end failed: ' + r.error, 'error'); pi_extension_pi_send_message(pi, 'hook-error', 'Hook agent_end failed: ' + r.error, 'error'); }
        } catch(e) {
        ctx.ui.notify('Hook agent_end error: ' + (e.message || String(e)), 'error');
        pi_extension_pi_send_message(pi, 'hook-error', 'Hook agent_end error: ' + (e.message || String(e)), 'error');

        }
      }, debounceMs);
    } catch(e) {
      ctx.ui.notify('Hook agent_end debounce error: ' + (e.message || String(e)), 'error');
      pi_extension_pi_send_message(pi, 'hook-error', 'Hook agent_end debounce error: ' + (e.message || String(e)), 'error');
    }
  });

  // Event hook: tool_result
  pi.on('tool_result', async (event, ctx) => {
    try {

      const hook_on_tool_result_on_tool_result = (await import('./build/dev/javascript/psypi/hook_on_tool_result.mjs')).on_tool_result;
      const result = await hook_on_tool_result_on_tool_result(JSON.stringify(event.result || ''), event.toolName || '', pi);
      const r = unwrapGleamResult(result);
      if (r.ok) {  }
      else { ctx.ui.notify('Hook tool_result failed: ' + r.error, 'error'); pi_extension_pi_send_message(pi, 'hook-error', 'Hook tool_result failed: ' + r.error, 'error'); }
      await record_trigger('tool_result');

    } catch(e) {
      ctx.ui.notify('Hook tool_result error: ' + (e.message || String(e)), 'error');
      pi_extension_pi_send_message(pi, 'hook-error', 'Hook tool_result error: ' + (e.message || String(e)), 'error');

    }
  });

  // Get the calling agent's ID. Returns S- prefix when called by the Somatic Agentbot (prompt-driven), A- prefix when called by the Autonomic Agentbot (event-driven). ID includes model and thinking level from live ctx.
  pi.registerTool({
    name: "psypi-my-id",
    description: "Get the calling agent's ID. Returns S- prefix when called by the Somatic Agentbot (prompt-driven), A- prefix when called by the Autonomic Agentbot (event-driven). ID includes model and thinking level from live ctx.",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await agent_identity_get_resolved_identity(({ is_idle: ctx.isIdle(), project: (function(){ var cwd = ctx.cwd || ''; if(!cwd) return 'non-project'; var parts = cwd.split('/').filter(Boolean); var dir = parts.pop() || ''; try { require('fs').statSync(cwd + '/.git'); return dir; } catch(e) { return 'non-project'; } }()), source: (ctx.model?.provider || ''), model: (ctx.model?.id || ''), thinking_level: (ctx.model?.thinkingLevel || ''), global: (function(){ var cwd = ctx.cwd || ''; if(!cwd) return true; try { require('fs').statSync(cwd + '/.git'); return false; } catch(e) { return true; } }()) }));
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-my-id error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-my-id exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Add a new task
  pi.registerTool({
    name: "psypi-task-add",
    description: "Add a new task",
    parameters: { "type": "object",
    "properties": {
      "title": { "type": "string" }
    },
    "required": ["title"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await task_add(params.title || "", "", 5, "cli");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-task-add error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Task: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-task-add exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List tasks, optionally filtered by status and project_id
  pi.registerTool({
    name: "psypi-tasks",
    description: "List tasks, optionally filtered by status and project_id",
    parameters: { "type": "object",
    "properties": {
      "status": { "type": "string" },
      "project_id": { "type": "string" }
    },
    "required": []
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await task_list(params?.status || null, params?.project_id || null);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-tasks error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-tasks exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Mark a task as completed
  pi.registerTool({
    name: "psypi-task-complete",
    description: "Mark a task as completed",
    parameters: { "type": "object",
    "properties": {
      "task_id": { "type": "string" }
    },
    "required": ["task_id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await task_complete(params.task_id || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-task-complete error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Task completed: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-task-complete exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Show project statistics (tasks, issues, skills, meetings)
  pi.registerTool({
    name: "psypi-stats-show",
    description: "Show project statistics (tasks, issues, skills, meetings)",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await stats_stats();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-stats-show error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Tasks:${r.value.tasks} Issues:${r.value.issues} Skills:${r.value.skills} Meetings:${r.value.meetings}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-stats-show exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Save a file version to code_versions table (auto-backup before AI edits)
  pi.registerTool({
    name: "psypi-doc-save",
    description: "Save a file version to code_versions table (auto-backup before AI edits)",
    parameters: { "type": "object",
    "properties": {
      "file_path": { "type": "string" }
    },
    "required": ["file_path"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await code_version_save_version(params.file_path || "", params.content || "", params.saved_by || "unknown", params.commit_hash || "", params.reason || "manual save");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-doc-save error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-doc-save exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List version history for a file
  pi.registerTool({
    name: "psypi-doc-list",
    description: "List version history for a file",
    parameters: { "type": "object",
    "properties": {
      "file_path": { "type": "string" },
      "limit": { "type": "string" }
    },
    "required": ["file_path", "limit"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await code_version_get_versions(params.file_path || "", parseInt(params.limit || '10'));
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-doc-list error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-doc-list exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Add a new issue
  pi.registerTool({
    name: "psypi-issue-add",
    description: "Add a new issue",
    parameters: { "type": "object",
    "properties": {
      "title": { "type": "string" },
      "description": { "type": "string" },
      "severity": { "type": "string" },
      "issue_type": { "type": "string" }
    },
    "required": ["title", "description", "severity", "issue_type"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await issue_db_add(params.title || "", params.description || "", params.severity || "medium", params.issue_type || "bug", params.created_by || "psypi");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-issue-add error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Issue added: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-issue-add exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List issues with filtering (status, severity, type) and pagination
  pi.registerTool({
    name: "psypi-issues",
    description: "List issues with filtering (status, severity, type) and pagination",
    parameters: { "type": "object",
    "properties": {
      "status": { "type": "string" },
      "severity": { "type": "string" },
      "issue_type": { "type": "string" },
      "project_id": { "type": "string" }
    },
    "required": []
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await issue_db_list(params?.status || null, params?.severity || null, params?.issue_type || null, params?.project_id || null, parseInt(params?.limit || '50'), parseInt(params?.offset || '0'));
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-issues error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Issues: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-issues exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Count issues matching filters (status, severity, type)
  pi.registerTool({
    name: "psypi-issue-count",
    description: "Count issues matching filters (status, severity, type)",
    parameters: { "type": "object",
    "properties": {
      "status": { "type": "string" },
      "severity": { "type": "string" },
      "issue_type": { "type": "string" },
      "project_id": { "type": "string" }
    },
    "required": []
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await issue_db_count(params?.status || null, params?.severity || null, params?.issue_type || null, params?.project_id || null);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-issue-count error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Count: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-issue-count exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get a single issue by ID
  pi.registerTool({
    name: "psypi-issue-get",
    description: "Get a single issue by ID",
    parameters: { "type": "object",
    "properties": {
      "id": { "type": "string" }
    },
    "required": ["id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await issue_db_get(params.id || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-issue-get error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Issue: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-issue-get exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Resolve an issue by ID
  pi.registerTool({
    name: "psypi-issue-resolve",
    description: "Resolve an issue by ID",
    parameters: { "type": "object",
    "properties": {
      "id": { "type": "string" }
    },
    "required": ["id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await issue_db_resolve(params.id || "", params.resolution || "resolved");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-issue-resolve error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Issue resolved: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-issue-resolve exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List skills, optionally filtered by status
  pi.registerTool({
    name: "psypi-skill-list",
    description: "List skills, optionally filtered by status",
    parameters: { "type": "object",
    "properties": {
      "status": { "type": "string" }
    },
    "required": []
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await skill_list(params?.status || null);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-skill-list error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Skills: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-skill-list exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get a skill by ID
  pi.registerTool({
    name: "psypi-skill-get",
    description: "Get a skill by ID",
    parameters: { "type": "object",
    "properties": {
      "id": { "type": "string" }
    },
    "required": ["id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await skill_get(params.id || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-skill-get error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Skill: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-skill-get exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Search skills by name
  pi.registerTool({
    name: "psypi-skill-search",
    description: "Search skills by name",
    parameters: { "type": "object",
    "properties": {
      "query": { "type": "string" }
    },
    "required": ["query"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await skill_search(params.query || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-skill-search error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Search results: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-skill-search exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List meetings, optionally filtered by status
  pi.registerTool({
    name: "psypi-meetings",
    description: "List meetings, optionally filtered by status",
    parameters: { "type": "object",
    "properties": {
      "status": { "type": "string" }
    },
    "required": []
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await meeting_list(params?.status || null);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-meetings error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Meetings: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-meetings exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get a meeting by ID
  pi.registerTool({
    name: "psypi-meeting-get",
    description: "Get a meeting by ID",
    parameters: { "type": "object",
    "properties": {
      "id": { "type": "string" }
    },
    "required": ["id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await meeting_get(params.id || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-meeting-get error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Meeting: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-meeting-get exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List opinions for a meeting
  pi.registerTool({
    name: "psypi-meeting-opinions",
    description: "List opinions for a meeting",
    parameters: { "type": "object",
    "properties": {
      "meeting_id": { "type": "string" }
    },
    "required": ["meeting_id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await meeting_list_opinions(params.meeting_id || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-meeting-opinions error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Opinions: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-meeting-opinions exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Add a new meeting
  pi.registerTool({
    name: "psypi-meeting-add",
    description: "Add a new meeting",
    parameters: { "type": "object",
    "properties": {
      "topic": { "type": "string" },
      "created_by": { "type": "string" }
    },
    "required": ["topic"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await meeting_create(params.topic || "", params.created_by || "psypi");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-meeting-add error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Meeting created: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-meeting-add exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Add an opinion to a meeting
  pi.registerTool({
    name: "psypi-meeting-say",
    description: "Add an opinion to a meeting",
    parameters: { "type": "object",
    "properties": {
      "meeting_id": { "type": "string" },
      "message": { "type": "string" }
    },
    "required": ["meeting_id", "message"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await meeting_add_opinion(params.meeting_id || "", params.author || "psypi", params.message || "", null, null);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-meeting-say error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Opinion added: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-meeting-say exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Save a learning to memory
  pi.registerTool({
    name: "psypi-learn-save",
    description: "Save a learning to memory",
    parameters: { "type": "object",
    "properties": {
      "content": { "type": "string" },
      "tags": { "type": "string" },
      "importance": { "type": "string" }
    },
    "required": ["content", "tags", "importance"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await learning_save(params.content || "", (() => { const t = (params.tags || '').trim(); if (!t) return '{}'; if (t.startsWith('[')) { try { const arr = JSON.parse(t); return '{' + arr.map(s => String(s).trim()).join(',') + '}'; } catch(e) { return '{' + t + '}'; } } return '{' + t.split(',').map(s => s.trim()).join(',') + '}'; })(), parseInt(params.importance || '5'), 'psypi');
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-learn-save error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Learning saved` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-learn-save exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Search memories by keyword
  pi.registerTool({
    name: "psypi-memory-search",
    description: "Search memories by keyword",
    parameters: { "type": "object",
    "properties": {
      "query": { "type": "string" },
      "limit": { "type": "string" }
    },
    "required": ["query", "limit"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await memory_search(params.query || '', parseInt(params.limit || '10'));
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-memory-search error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Found {count} memories` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-memory-search exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Send a broadcast message
  pi.registerTool({
    name: "psypi-broadcast-send",
    description: "Send a broadcast message",
    parameters: { "type": "object",
    "properties": {
      "message": { "type": "string" },
      "priority": { "type": "string" },
      "project_id": { "type": "string" }
    },
    "required": ["message", "priority", "project_id"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await broadcast_send('psypi', params.message || "", params.priority || 'normal', params.project_id || "");
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-broadcast-send error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Broadcast sent: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-broadcast-send exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List broadcast messages
  pi.registerTool({
    name: "psypi-broadcasts",
    description: "List broadcast messages",
    parameters: { "type": "object",
    "properties": {
      "limit": { "type": "string" }
    },
    "required": ["limit"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await broadcast_list(null, parseInt(params.limit || '10'));
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-broadcasts error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Broadcasts: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-broadcasts exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Extract [LEARN], [ISSUE], [TASK], [ISSUELIST] markers from text and save to database
  pi.registerTool({
    name: "psypi-areflect",
    description: "Extract [LEARN], [ISSUE], [TASK], [ISSUELIST] markers from text and save to database",
    parameters: { "type": "object",
    "properties": {
      "text": { "type": "string" }
    },
    "required": ["text"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await areflect_areflect(params.text || "", 'psypi');
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-areflect error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Reflection: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-areflect exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List all registered agents
  pi.registerTool({
    name: "psypi-agents",
    description: "List all registered agents",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await agents_list();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-agents error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `Agents: ${JSON.stringify(r.value)}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-agents exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get psypi Monitor status and capabilities
  pi.registerTool({
    name: "psypi-autonomic-status",
    description: "Get psypi Monitor status and capabilities",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await monitor_ai_start_monitor_loop();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-autonomic-status error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `psypi Monitor: OK - use psypi-autonomic-health for metrics` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-autonomic-status exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get system health metrics (failed tasks, open issues, activity)
  pi.registerTool({
    name: "psypi-autonomic-health",
    description: "Get system health metrics (failed tasks, open issues, activity)",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await monitor_ai_check_system_health();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-autonomic-health error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-autonomic-health exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get active alerts (failed tasks, open issues)
  pi.registerTool({
    name: "psypi-autonomic-alerts",
    description: "Get active alerts (failed tasks, open issues)",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await monitor_ai_get_alerts();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-autonomic-alerts error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-autonomic-alerts exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get Monitor statistics (review scores, response times, failure rate)
  pi.registerTool({
    name: "psypi-autonomic-stats",
    description: "Get Monitor statistics (review scores, response times, failure rate)",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await monitor_ai_get_model_stats();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-autonomic-stats error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-autonomic-stats exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Get work suggestions from Monitor (open issues, stale tasks, pending skills)
  pi.registerTool({
    name: "psypi-autonomic-suggest",
    description: "Get work suggestions from Monitor (open issues, stale tasks, pending skills)",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await monitor_ai_get_work_suggestions();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-autonomic-suggest error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-autonomic-suggest exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List all psypi event hooks and their status (Monitor's awareness table)
  pi.registerTool({
    name: "psypi-hooks-list",
    description: "List all psypi event hooks and their status (Monitor's awareness table)",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await event_hooks_list_all_hooks();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-hooks-list error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-hooks-list exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // List only active psypi event hooks (those with hook_status='active')
  pi.registerTool({
    name: "psypi-hooks-active",
    description: "List only active psypi event hooks (those with hook_status='active')",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await event_hooks_list_active_hooks();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-hooks-active error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-hooks-active exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Direct the Somatic Agentbot. Only the Autonomic Agentbot should use this. Gets Autonomic identity (model-aware from ctx), includes SOUL context. The directive will be injected into the Somatic Agentbot's system prompt on its next turn.
  pi.registerTool({
    name: "psypi-direct-agentbot",
    description: "Direct the Somatic Agentbot. Only the Autonomic Agentbot should use this. Gets Autonomic identity (model-aware from ctx), includes SOUL context. The directive will be injected into the Somatic Agentbot's system prompt on its next turn.",
    parameters: { "type": "object",
    "properties": {
      "directive_text": { "type": "string" },
      "priority": { "type": "string" }
    },
    "required": ["directive_text"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await directive_set_directive(params.directive_text || "", params.priority || "medium", ctx.model?.id || '', (ctx.model?.thinkingLevel || ''));
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-direct-agentbot error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-direct-agentbot exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Clear all active system directives.
  pi.registerTool({
    name: "psypi-clear-directives",
    description: "Clear all active system directives.",
    parameters: { "type": "object", "properties": {} },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await directive_clear_directives();
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-clear-directives error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: `${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-clear-directives exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Consult the Autonomic Worker for difficult decisions. Only the Somatic Worker should use this.
  pi.registerTool({
    name: "psypi-consult-autonomic",
    description: "Consult the Autonomic Worker for difficult decisions. Only the Somatic Worker should use this.",
    parameters: { "type": "object",
    "properties": {
      "question": { "type": "string" }
    },
    "required": ["question"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await tool_consult_on_consult(params.question || '', ctx);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-consult-autonomic error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-consult-autonomic exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Commit with Monitor inter-review.
  pi.registerTool({
    name: "psypi-commit",
    description: "Commit with Monitor inter-review.",
    parameters: { "type": "object",
    "properties": {
      "message": { "type": "string" },
      "review_id": { "type": "string" }
    },
    "required": ["message"]
  },
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      try {
        const result = await tool_commit_on_commit(params.message || '', params.review_id || '', ctx, pi);
        const r = unwrapGleamResult(result);
        if (!r.ok) {
          pi_extension_notify_error(ctx, 'Tool psypi-commit error: ' + r.error);
        }
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        pi_extension_notify_error(ctx, 'Tool psypi-commit exception: ' + (e.message || String(e)));
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Talk to Monitor AI directly - human and Monitor exchange in chat
  pi.registerCommand("autonomic-listen", {
    description: "Talk to Monitor AI directly - human and Monitor exchange in chat",
    handler: async (args, ctx) => {
      try {
        const command_listen_on_autonomic_listen = (await import('./build/dev/javascript/psypi/command_listen.mjs')).on_autonomic_listen;
        const result = await command_listen_on_autonomic_listen(args || '', ctx, pi);
        const r = unwrapGleamResult(result);
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

  // Reload Pi extensions - used after Monitor modifies its own Gleam code
  pi.registerCommand("autonomic-reload", {
    description: "Reload Pi extensions - used after Monitor modifies its own Gleam code",
    handler: async (args, ctx) => {
      try {
        const command_reload_on_autonomic_reload = (await import('./build/dev/javascript/psypi/command_reload.mjs')).on_autonomic_reload;
        const result = await command_reload_on_autonomic_reload(ctx);
        const r = unwrapGleamResult(result);
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) {
        return { content: [{ type: "text", text: `Error: ${e.message || String(e)}` }] };
      }
    }
  });

}
