-- Bulk insert findings from SYSTEM-REVIEW-2026-05-26.md
-- Review ID: ca9e914c-cce6-4db4-b3b1-29779d8e1837
-- Each finding verified against live database and source code

-- Category 1: Missing ::text casts (14 findings)
INSERT INTO review_findings (review_id, finding_number, severity, category, module, title, description, evidence, impact) VALUES
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 100, 'critical', 'missing_cast', 'inter_review', 'inter_review requested_at decode fails without ::text cast', 'SELECT * returns timestamptz without cast; node-postgres returns Date object which Gleam decode.string cannot parse', 'inter_review.gleam: requested_at field decoded as string but SELECT * returns timestamptz', 'Inter-review requests always fail to decode'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 101, 'high', 'missing_cast', 'inter_review', 'inter_review id not cast to text', 'UUID columns need ::text cast for Gleam string decoder', 'inter_review.gleam: id is uuid, decoded as string without cast', 'Decode may fail or return [object Object]'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 102, 'high', 'missing_cast', 'memory', 'memory.search SELECT * returns uuid/timestamptz without casts', 'SELECT * FROM memory returns created_at as timestamptz and id as uuid, both need ::text', 'memory.gleam search(): SELECT * FROM memory WHERE content ILIKE $1', 'memory.search always returns DecodeError'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 103, 'high', 'missing_cast', 'skill', 'skill.get missing ::text casts on content and reference_list', 'content is text (ok) but reference_list is jsonb, needs ::text for Gleam decoder', 'skill.gleam get(): reference_list decoded without ::text cast', 'Skill details may fail to decode'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 104, 'medium', 'missing_cast', 'task', 'task.get missing project_id::text in SELECT', 'project_id is uuid, needs ::text cast for Gleam string decoder', 'task.gleam get(): project_id not cast to text', 'Task get may fail to decode project_id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 105, 'medium', 'missing_cast', 'task', 'task.list id not cast to text', 'id is uuid in tasks table but not cast in list query', 'task.gleam list(): id column not cast', 'Task list may fail to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 106, 'medium', 'missing_cast', 'agents', 'agents.list missing ::text cast on created_at', 'created_at is timestamptz, needs ::text for Gleam decoder', 'agents.gleam list(): created_at not cast', 'Agent list may fail to decode'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 107, 'medium', 'missing_cast', 'monitor', 'monitor.get_pending_notifications read_at cast mismatch', 'read_at is timestamptz but may be decoded inconsistently', 'monitor.gleam: read_at handling inconsistent', 'Notification queries may fail'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 108, 'medium', 'missing_cast', 'code_version', 'code_version.query_versions missing ::text casts', 'Multiple timestamptz/uuid columns not cast', 'code_version.gleam query_versions(): missing casts', 'Version queries may fail to decode'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 109, 'high', 'missing_cast', 'areflect', 'areflect.fetch_recent_issues missing ::text casts for uuid and timestamps', 'id is uuid, created_at/resolved_at are timestamptz, all need ::text', 'areflect.gleam fetch_recent_issues(): SELECT without casts', 'Recent issues fetch always fails'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 110, 'medium', 'missing_cast', 'a_db_reader', 'a_db_reader multiple queries missing ::text casts', 'read_a_soul, read_active_tasks, read_open_issues all have uncast columns', 'a_db_reader.gleam: multiple SELECT queries without casts', 'A-agent reads may fail silently'),

-- Category 2: Wrong status values (6 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 111, 'high', 'wrong_status', 'monitor_ai', 'check_system_health uses FAILED for tasks but DB has PENDING/COMPLETED', 'tasks.status CHECK allows PENDING/COMPLETED only; FAILED does not exist', 'monitor_ai.gleam check_system_health(): WHERE status != ''FAILED''', 'Health metrics for tasks always return 0'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 112, 'high', 'wrong_status', 'monitor_ai', 'analyze_and_act same status value bugs as check_system_health', 'Same FAILED status issue propagated to analyze_and_act', 'monitor_ai.gleam analyze_and_act(): same wrong status', 'Analysis always misses task data'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 113, 'medium', 'wrong_status', 'monitor_ai', 'get_model_stats case-sensitive status comparison', 'Compares status as text but DB stores uppercase', 'monitor_ai.gleam get_model_stats(): status comparison', 'Model stats may miss records'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 114, 'medium', 'wrong_status', 'task', 'task.string_to_status accepts both cases but DB is uppercase', 'DB CHECK allows PENDING/COMPLETED (uppercase); code accepts both', 'task.gleam string_to_status(): case-insensitive matching', 'Inconsistency between insert and query'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 115, 'medium', 'wrong_status', 'issue_types', 'IssueStatus Gleam type vs DB CHECK mismatch', 'DB has open/acknowledged/in_progress/resolved/wont_fix/duplicate; Gleam has Open/InProgress/Resolved/Closed', 'issue_types.gleam: missing acknowledged/wont_fix/duplicate, extra Closed', 'Decode fails for acknowledged/wont_fix/duplicate statuses'),

-- Category 3: Missing project_id (8 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 116, 'critical', 'missing_project_id', 'areflect', 'areflect.save_issue omits project_id (NOT NULL, no default)', 'INSERT INTO issues (title, description, severity, created_by) — missing project_id column', 'areflect.gleam save_issue(): 4-column INSERT into 6-column table', 'save_issue INSERT always fails; no issues can be saved via areflect'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 117, 'high', 'missing_project_id', 'areflect', 'areflect.save_task missing project_id (has default but wrong)', 'Uses DEFAULT for project_id which may assign to wrong project', 'areflect.gleam save_task(): relies on DB default', 'Tasks may be assigned to wrong project'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 118, 'high', 'missing_project_id', 'monitor_ai', 'auto_file_issue uses non-existent column type, missing project_id', 'INSERT uses column "type" which does not exist; also missing project_id', 'monitor_ai.gleam auto_file_issue(): INSERT with wrong column name', 'Auto-issue filing always fails'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 119, 'medium', 'missing_project_id', 'a_db_reader', 'a_db_reader.read_active_tasks no project_id filter', 'SELECT from tasks without WHERE project_id = ...', 'a_db_reader.gleam read_active_tasks(): no project filter', 'Returns tasks from all projects'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 120, 'medium', 'missing_project_id', 'broadcast', 'broadcast.send empty string for UUID NOT NULL column', 'Uses empty string for project_id which is uuid NOT NULL', 'broadcast.gleam send(): project_id = empty string', 'Broadcast send fails on NOT NULL constraint'),

-- Category 4: FFI type mismatches (5 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 121, 'critical', 'ffi_mismatch', 'pi_extension_ffi', 'get_config returns JS null/string not Gleam Option', 'Gleam expects Some(value)/None but JS returns null or string; pattern matching never works', 'pi_extension_ffi.mjs: return _configStore[key] || null', 'A-bot debounce never fires; idle_since always reset; A-bot completely dead'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 122, 'high', 'ffi_mismatch', 'pi_extension_ffi', 'set_config stores value but get_config cannot retrieve as Gleam Option', 'Even if set_config works, get_config breaks the Option contract', 'pi_extension_ffi.mjs: set_config stores, get_config returns raw', 'Config round-trip broken'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 123, 'high', 'ffi_mismatch', 'pi_extension_ffi', 'unwrapGleamResult may not handle all Gleam Result shapes', 'Gleam Result is {type: "Ok"/"Error", ...} but unwrap logic may miss edge cases', 'pi_extension_ffi.mjs: unwrapGleamResult()', 'Error handling in extension.js may fail'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 124, 'medium', 'ffi_mismatch', 'pi_extension_ffi', 'ctx_is_idle/ctx_has_pending_messages return JS booleans not Gleam Bool', 'Gleam Bool is JS true/false so this actually works, but the type signature uses untyped `a`', 'pi_extension.gleam: ctx_is_idle(ctx: a) -> Bool', 'Works by accident; fragile to Gleam compiler changes'),

-- Category 5: Two config systems (2 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 125, 'high', 'config_desync', 'psypi_config', 'psypi_config.gleam (database) vs pi_extension_ffi.mjs (in-memory) never sync', 'Two independent config systems with different values for same keys', 'psypi_config reads from DB; pi_extension_ffi uses _configStore object', 'hook_on_agent_end uses 5min debounce; monitor_ai uses 15min debounce'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 126, 'medium', 'config_desync', 'seed', 'seed.gleam seeds monitor_debounce_ms as 300000 but DB has 900000', 'Seed script and existing data disagree on debounce value', 'seed.gleam: 300000 vs psypi_config table: 900000', 'Fresh installs get different debounce than existing deployments'),

-- Category 6: Disconnected learning systems (2 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 127, 'medium', 'disconnected_systems', 'areflect', 'areflect saves to learning_insights; learning.gleam saves to memory; neither reads the other', 'Two separate tables for the same concept (learned insights)', 'areflect.gleam → learning_insights; learning.gleam → memory', 'No unified learning retrieval; insights fragmented'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 128, 'medium', 'disconnected_systems', 'areflect', 'areflect.save_learning ignores agent_id parameter', 'Parameter _agent_id is accepted but not used in INSERT', 'areflect.gleam save_learning(): _agent_id unused', 'Cannot attribute learnings to specific agents'),

-- Category 7: Missing tool parameters (5 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 129, 'high', 'missing_params', 'code_version', 'psypi-doc-save only declares file_path but uses 5 parameters', 'params: [file_path] but args references content, saved_by, commit_hash, reason', 'code_version.gleam doc_save_tool(): 1 param declared, 5 used', 'Content always empty; saved versions have no content'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 130, 'low', 'missing_params', 'issue_tools', 'psypi-issue-add references created_by not in params', 'created_by used in args but not declared in params schema', 'issue_tools.gleam: params.created_by always undefined', 'Always defaults to "psypi"'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 131, 'low', 'missing_params', 'issue_tools', 'psypi-issues does not declare limit/offset in params', 'AI cannot control pagination beyond first 50 results', 'issue_tools.gleam: limit/offset not in params', 'No way to page through results'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 132, 'medium', 'missing_params', 'memory', 'memory.memory_search_tool result template uses literal {count}', 'Template has ${count} but count is not a variable in scope', 'memory.gleam: template("Found {count} memories")', 'Result message shows literal {count} not actual number'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 133, 'medium', 'missing_params', 'agent_identity', 'psypi-my-id missing project and global fields', 'lit() expression does not include project or global fields', 'agent_identity.gleam my_id_tool(): missing project/global', 'Semantic ID becomes S-undefined-... instead of S-psypi-...'),

-- Category 8: Hardcoded project_id (3 findings)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 134, 'medium', 'hardcoded_config', 'issue_db', 'issue_db.get() and resolve() hardcode project_id UUID', 'UUID hardcoded instead of using session variable', 'issue_db.gleam: "0d324e68-b399-4b85-bd8a-6b1ef7b46168"', 'Only works for one project; breaks if project_id changes'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 135, 'medium', 'hardcoded_config', 'issue_db', 'issue_db.list() comment says session variable but hardcodes UUID', 'Comment claims "from session variable" but code hardcodes', 'issue_db.gleam build_where(): misleading comment', 'False documentation; actual behavior differs from stated'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 136, 'medium', 'hardcoded_config', 'db', 'db.connect() sets app.current_project_id but no module reads it', 'Session variable set on every connection but never used in queries', 'db.gleam connect(): SET app.current_project_id = $1', 'Dead code; creates false sense of project isolation'),

-- Category 9: No connection pooling (1 finding)
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 137, 'high', 'performance', 'db', 'db.with_connection() creates new TCP connection per query', 'Every query: connect → auth → SET variable → query → disconnect', 'db.gleam with_connection(): no pooling, uses pg.Client not pg.Pool', '3-10x latency overhead; potential connection exhaustion'),

-- Additional critical findings from deeper review
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 138, 'high', 'wrong_decoder', 'memory', 'memory.save() decodes RETURNING id with full memory_decoder()', 'INSERT RETURNING id returns 1 column but decoder expects all Memory fields', 'memory.gleam save(): decode.run(row, memory_decoder()) on RETURNING id', 'Save always reports error (data IS saved but error returned)'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 139, 'high', 'logic_error', 'broadcast', 'broadcast.stats() 3 bugs: bigint decode, text>=int, missing status column', 'COUNT(*) returns bigint (needs ::INT), status compared as text>=int, status column missing from GROUP BY', 'broadcast.gleam stats(): multiple query errors', 'Stats query returns wrong results or fails'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 140, 'medium', 'logic_error', 'agent_identity', 'semantic_id uses is_idle for A/S prefix; idle S-agent gets wrong identity', 'is_idle=True → "A" prefix, but idle S-agent should still be "S"', 'agent_identity_types.gleam semantic_id(): is_idle determines prefix', 'Idle S-agent gets A- prefix; wrong session tracking'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 141, 'medium', 'logic_error', 'hook_on_agent_end', 'hook_on_tool_result synchronous return in async context', 'Returns Result synchronously but caller expects Promise', 'hook_on_agent_end.gleam: sync return in async hook', 'Hook may not properly chain with other hooks'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 142, 'medium', 'error_handling', 'pi_extension', 'pi_send_message fire-and-forget; no error feedback', 'Returns Nil synchronously; no way to know if message was sent', 'pi_extension.gleam: pi_send_message returns Nil', 'A→S communication failures are silent'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 143, 'low', 'error_handling', 'issue_db', 'issue_db.count() returns Ok(0) on decode failure', 'Error(_) -> Ok(0) silently swallows decode errors', 'issue_db.gleam count(): Error(_) -> Ok(0)', 'Reports 0 issues when decode fails; misleading'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 144, 'low', 'error_handling', 'a_db_reader', 'a_db_reader reports Ok(True) on decode failure', 'Error(_) -> Ok(True) returns "no sessions" on any error', 'a_db_reader.gleam: Error(_) -> Ok(True)', 'Errors hidden; always reports no sessions'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 145, 'medium', 'dead_code', 'monitor_ai', 'housekeeping() is a test stub left in production', 'Function body is placeholder/test code', 'monitor_ai.gleam housekeeping(): stub implementation', 'Dead code in production module'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 146, 'medium', 'design_flaw', 'monitor_ai', 'monitor_ai.prepare_context UNION ALL with mismatched columns', 'UNION ALL queries have different column counts/types', 'monitor_ai.gleam prepare_context(): UNION ALL mismatch', 'Context preparation may fail or return wrong data'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 147, 'medium', 'design_flaw', 'hook_on_before_agent_start', 'Error fallback includes hardcoded soul content', 'On error, returns hardcoded soul instead of graceful failure', 'hook_on_before_agent_start.gleam: hardcoded fallback soul', 'Errors masked by fake soul data'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 148, 'low', 'style', 'command_reload', 'command_reload only notifies; no error handling', 'notify_info called but no error path', 'command_reload.gleam: no error handling', 'Reload failures are silent'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 149, 'medium', 'design_flaw', 'extension_generator', 'Dynamic imports in every hook trigger', 'Each hook invocation dynamically imports the module', 'extension_generator.gleam: dynamic import per hook call', 'Performance overhead on every hook trigger'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 150, 'low', 'design_flaw', 'hook_on_tool_call', 'Only triggers on tool named "edit"', 'Hook checks event.toolName === "edit" only', 'hook_on_tool_call.gleam: edit-only trigger', 'Other tool calls not tracked');
