INSERT INTO review_findings (review_id, finding_number, severity, category, module, title, description, evidence, impact) VALUES
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 151, 'medium', 'design_flaw', 'audit_trigger', 'Audit trigger source=learn not in allowed sources', 'learning_insights audit trigger allows source IN (agent,system,hook,tool) but not learn; areflect saves with source=learn', 'SQL migration: CHECK source IN (...) missing learn', 'areflect save_learning may fail audit trigger validation'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 152, 'low', 'test_coverage', 'test', 'Gleam test files import modules that dont exist', 'Test imports reference modules not in src/ directory', 'test/*.gleam: import paths broken', 'Tests cannot compile; false positive pass rate'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 153, 'medium', 'ffi_mismatch', 'pi_extension_ffi', 'gleamValueToJson uses constructor.name which breaks under minification', 'Pattern matching on constructor.name is fragile; breaks if JS is minified', 'pi_extension_ffi.mjs: constructor.name checks', 'Type detection fails in production if code is minified'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 154, 'medium', 'design_flaw', 'pi_extension_ffi', 'Duplicate now_ms FFI in both pi_extension_ffi.mjs and time_ffi.mjs', 'Two separate FFI implementations for getting current time in ms', 'pi_extension_ffi.mjs: now_ms(); time_ffi.mjs: now_ms()', 'Inconsistency; which one is authoritative?'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 155, 'high', 'security', 'pi_extension_ffi', 'exec_sync allows command injection via unsanitized input', 'exec_sync(command) runs shell command directly; no input sanitization', 'pi_extension_ffi.mjs: exec_sync(cmd)', 'Arbitrary command execution if tool params contain shell metacharacters'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 156, 'medium', 'design_flaw', 'monitor_ai', 'call_monitor retry without exponential backoff', 'Retries on failure but uses fixed delay, not exponential backoff', 'pi_extension_ffi.mjs: call_monitor() retry logic', 'Retry storms under load; no jitter'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 157, 'low', 'style', 'pi_extension_ffi', 'Orphan FFI file not imported by any Gleam module', 'FFI file exists but no corresponding Gleam external function', 'pi_extension_ffi.mjs: orphan exports', 'Dead code in FFI layer'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 158, 'medium', 'design_flaw', 'package', 'Package namespace mismatch between gleam.toml and import paths', 'Package name in gleam.toml may not match actual import structure', 'gleam.toml: name vs actual module paths', 'Import resolution may fail for external consumers'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 159, 'medium', 'error_handling', 'multiple', 'Error handling anti-pattern: Ok(0) on decode failure in 4+ modules', 'Multiple modules return Ok(default) when decode fails, hiding errors', 'issue_db count(), a_db_reader read_*, memory search()', 'Silent data loss; errors never surface'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 160, 'medium', 'logic_error', 'hook_on_agent_end', 'A/S agent debounce logic: idle_since reset on every tool call', 'get_config returns JS null (not Gleam None) so pattern match always hits Some branch', 'hook_on_agent_end.gleam: idle_since reset logic', 'A-bot never goes idle; debounce never triggers; S-bot never activated'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 161, 'low', 'test_coverage', 'test', 'No integration tests for database queries', 'All Gleam test files are unit tests; no test actually connects to PostgreSQL', 'test/ directory: no DB integration tests', 'DB query bugs never caught by tests'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 162, 'medium', 'security', 'db', 'SQL injection risk: string interpolation in WHERE clauses', 'build_where functions concatenate user input into SQL strings', 'issue_db.gleam, task.gleam: string concatenation in SQL', 'Potential SQL injection if filter values contain SQL metacharacters'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 163, 'low', 'style', 'git', 'Git state shows AI repair pattern: many fix commits without verification', 'Commit history shows pattern of fix-attempt-fix without testing between', 'git log: fix/repair/revert pattern', 'Unverified fixes may introduce new bugs');
