-- Corrections to existing findings
UPDATE review_findings SET status = 'retracted', description = description || ' [RETRACTED: FAILED IS a valid task status per DB CHECK constraint: PENDING/RUNNING/COMPLETED/FAILED/FAKE_COMPLETE]', impact = 'Finding was incorrect; FAILED status exists in both DB and Gleam TaskStatus type' WHERE review_id = 'ca9e914c-cce6-4db4-b3b1-29779d8e1837' AND finding_number = 111;
UPDATE review_findings SET status = 'retracted', description = description || ' [RETRACTED: Same as #111, FAILED IS valid]', impact = 'Finding was incorrect' WHERE review_id = 'ca9e914c-cce6-4db4-b3b1-29779d8e1837' AND finding_number = 112;

-- Correction: #103 - bug is in get_by_name and search, not get
UPDATE review_findings SET description = 'skill.get_by_name() and search() have reference_list (jsonb) without ::text cast; get() has the cast', evidence = 'skill.gleam: lines 184,214 missing ::text on reference_list; lines 137,144 have it' WHERE review_id = 'ca9e914c-cce6-4db4-b3b1-29779d8e1837' AND finding_number = 103;

-- Correction: #139 - priority is text not int, no status column
UPDATE review_findings SET description = 'broadcast.stats() has 3 bugs: (1) priority is text (low/normal/high/critical) but query does priority >= 2 which is text>=int comparison — always fails; (2) WHERE status = sent but project_communications has no status column; (3) COUNT(*) returns bigint without ::INT cast', evidence = 'broadcast.gleam stats(): priority text>=2, status column does not exist in project_communications, COUNT(*) without ::INT', severity = 'critical' WHERE review_id = 'ca9e914c-cce6-4db4-b3b1-29779d8e1837' AND finding_number = 139;

-- Correction: #155 - exec_sync has shell_escape, reduce severity
UPDATE review_findings SET severity = 'medium', description = 'exec_sync runs shell commands; shell_escape() provides basic sanitization but may not cover all edge cases (newlines, semicolons, pipe characters)', evidence = 'pi_extension_ffi.mjs: exec_sync(cmd); tool_commit.gleam: shell_escape() covers backslash, quote, backtick, dollar sign' WHERE review_id = 'ca9e914c-cce6-4db4-b3b1-29779d8e1837' AND finding_number = 155;

-- New findings discovered during verification
INSERT INTO review_findings (review_id, finding_number, severity, category, module, title, description, evidence, impact) VALUES
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 200, 'high', 'missing_cast', 'agent_identity', 'agent_identity fetch_soul_by_prefix: id uuid without ::text', 'SELECT id, name, domain, responsibility, trigger_type, drive_mode, activation FROM agent_souls — id is uuid, decoder expects String', 'agent_identity.gleam:120 SELECT id without ::text cast', 'Soul fetch fails to decode; agent identity broken'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 201, 'high', 'missing_cast', 'meeting', 'meeting.gleam: id uuid without ::text in all SELECT queries', 'Lines 166,173,206,276 — id is uuid, decoder expects String', 'meeting.gleam: id column not cast to text', 'Meeting queries fail to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 202, 'high', 'missing_cast', 'agents', 'agents.gleam: id uuid without ::text', 'SELECT id, agent_type, created_at::text — id is uuid, decoder expects String', 'agents.gleam:52 SELECT id without ::text cast', 'Agent list fails to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 203, 'high', 'missing_cast', 'monitor', 'monitor.gleam get_pending_notifications: id uuid without ::text', 'SELECT id, agent_id, priority, title, body — id is uuid, decoder expects String', 'monitor.gleam:188 SELECT id without ::text cast', 'Notification queries fail to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 204, 'high', 'missing_cast', 'task', 'task.gleam: id uuid without ::text in list and get queries', 'Lines 182,240 — id is uuid, decoder expects String', 'task.gleam: id column not cast to text in list/get', 'Task queries fail to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 205, 'high', 'missing_cast', 'issue_db', 'issue_db.gleam: id uuid without ::text in list and get queries', 'Lines 166,267 — id is uuid, decoder expects String', 'issue_db.gleam: id column not cast to text', 'Issue queries fail to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 206, 'medium', 'wrong_status', 'a_db_reader', 'a_db_reader read_open_issues uses status=closed but DB has no closed status', 'WHERE status NOT IN (resolved,closed) — closed does not exist; DB has wont_fix and duplicate instead', 'a_db_reader.gleam:130 status NOT IN (resolved,closed)', 'Issues with wont_fix/duplicate status show as open when they shouldnt'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 207, 'medium', 'missing_cast', 'stats', 'stats.gleam COUNT(*) without ::text or ::INT; decode_bigint expects string', 'COUNT(*) returns bigint; decode_bigint uses decode.string but no ::text cast in SQL', 'stats.gleam:30 COUNT(*) without cast; stats_decoder uses decode_bigint', 'Stats query may fail to decode counts'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 208, 'medium', 'missing_cast', 'broadcast', 'broadcast.gleam stats(): COUNT(*) without ::INT cast', 'COUNT(*) as total returns bigint; decoder uses decode.int', 'broadcast.gleam:257 COUNT(*) without ::INT', 'Stats may fail to decode for large counts'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 209, 'medium', 'missing_cast', 'a_db_reader', 'a_db_reader is_s_still_idle: COUNT(*) without ::INT', 'COUNT(*) as cnt returns bigint; decoder uses decode.int', 'a_db_reader.gleam:33 COUNT(*) without ::INT', 'Session count may fail to decode for large values'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 210, 'medium', 'wrong_status', 'issue_types', 'IssueStatus missing acknowledged/wont_fix/duplicate; has Closed which DB doesnt have', 'DB CHECK: open/acknowledged/in_progress/resolved/wont_fix/duplicate. Gleam: Open/InProgress/Resolved/Closed. Missing 3, extra 1.', 'issue_types.gleam: string_to_status() maps closed->Closed but DB has no closed; acknowledged/wont_fix/duplicate cause Error', 'Decode fails for acknowledged/wont_fix/duplicate issues; Closed maps to non-existent DB status'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 211, 'medium', 'wrong_status', 'issue_types', 'IssueType missing proposal which DB allows', 'DB CHECK includes proposal; Gleam IssueType does not have Proposal variant', 'issue_types.gleam: string_to_type() — no proposal case', 'Decode fails for proposal-type issues'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 212, 'medium', 'missing_cast', 'meeting', 'meeting.gleam: meeting_id uuid without ::text in opinions query', 'SELECT id, meeting_id, author, perspective, reasoning — meeting_id is uuid without ::text', 'meeting.gleam:276 meeting_id not cast to text', 'Opinion queries fail to decode meeting_id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 213, 'low', 'missing_project_id', 'learning', 'learning.save() INSERT INTO memory omits project_id', 'INSERT INTO memory (content, tags, source, importance, agent_id) — no project_id', 'learning.gleam:28 INSERT without project_id', 'Memories not scoped to project; cross-project leakage possible'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 214, 'medium', 'missing_cast', 'task', 'task.gleam get(): id uuid without ::text, missing project_id in SELECT', 'SELECT id,...FROM tasks WHERE id=$1 — id not cast, project_id not selected', 'task.gleam:240 id without ::text, missing project_id column', 'Task get fails to decode id; Task record has no project_id');
