-- Additional findings from continued verification (batch 2)

INSERT INTO review_findings (review_id, finding_number, severity, category, module, title, description, evidence, impact) VALUES
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 215, 'critical', 'wrong_column', 'monitor_ai', 'monitor_ai record_tool_error: INSERT uses type instead of issue_type, discovered_by/environment columns dont exist', 'INSERT INTO issues (title, description, severity, type, created_by, discovered_by, environment) — column is issue_type not type; discovered_by and environment columns do not exist in issues table', 'monitor_ai.gleam:561 INSERT INTO issues with wrong column names; \\d issues shows issue_type not type, no discovered_by/environment', 'Tool error recording always fails; monitor cannot create issues for tool failures'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 216, 'high', 'missing_cast', 'code_version', 'code_version save_version: save_code_version() returns uuid but decoder uses decode.string without ::text', 'SELECT save_code_version(...) as version_id — function returns uuid, version_id_decoder uses decode.string', 'code_version.gleam:19 SELECT save_code_version() as version_id without ::text; version_id_decoder at line 84 uses decode.string', 'Save version always fails to decode the returned version_id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 217, 'high', 'missing_cast', 'code_version', 'code_version query_versions: id uuid and saved_at timestamptz without ::text', 'SELECT id, file_path, saved_by, saved_at — id is uuid, saved_at is timestamptz, no ::text casts', 'code_version.gleam:186-188 id and saved_at without ::text cast', 'Version history query returns undecodable uuid/timestamp values'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 218, 'high', 'missing_cast', 'code_version', 'code_version get_versions: get_code_versions() returns id uuid and saved_at timestamptz without ::text', 'SELECT * FROM get_code_versions() — returns TABLE(id uuid, ..., saved_at timestamptz, ...) without casts', 'code_version.gleam:66 SELECT * FROM get_code_versions(); \\df+ shows id uuid, saved_at timestamptz return types', 'Version list returns undecodable uuid/timestamp values'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 219, 'high', 'missing_cast', 'areflect', 'areflect read_recent_issues: id uuid without ::text', 'SELECT id, title, status, severity FROM issues — id is uuid, decoder expects String', 'areflect.gleam:133 SELECT id without ::text cast', 'Reflective analysis fails to decode issue ids'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 220, 'high', 'missing_cast', 'broadcast', 'broadcast.gleam: id uuid without ::text in all list queries', 'SELECT id, from_ai as agent_id, content as message, priority — id is uuid, decoder expects String', 'broadcast.gleam:196,204,233 SELECT id without ::text cast', 'Broadcast list queries fail to decode id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 221, 'high', 'missing_cast', 'inter_review', 'inter_review.gleam: id uuid and requested_at timestamptz without ::text in list queries', 'SELECT id, task_id, status, summary, overall_score, requested_at — id is uuid, task_id is uuid, requested_at is timestamptz', 'inter_review.gleam:148,283,285 id/task_id/requested_at without ::text', 'Inter-review list and get queries fail to decode'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 222, 'high', 'missing_cast', 'inter_review', 'inter_review.gleam: request_inter_review() returns uuid without ::text', 'SELECT request_inter_review(...) as review_id — function returns uuid, decoder uses decode.string', 'inter_review.gleam:184 as review_id without ::text; \\df+ shows return type uuid', 'Creating inter-review fails to decode returned review_id'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 223, 'medium', 'missing_project_id', 'monitor_ai', 'monitor_ai record_tool_error: INSERT INTO issues omits project_id', 'INSERT INTO issues (title, description, severity, type, created_by, discovered_by, environment) — no project_id', 'monitor_ai.gleam:561 INSERT without project_id', 'Tool error issues not scoped to project'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 224, 'medium', 'missing_project_id', 'areflect', 'areflect INSERT INTO issues and tasks omits project_id', 'INSERT INTO issues (title, description, severity, created_by) and INSERT INTO tasks (title, description, priority, created_by) — no project_id', 'areflect.gleam:224,262 INSERT without project_id', 'Reflective issues/tasks not scoped to project'),
('ca9e914c-cce6-4db4-b3b1-29779d8e1837', 225, 'low', 'design', 'simple_migrate', 'simple_migrate re-runs all migrations every time — no tracking of completed migrations', 'run_all_migrations() reads all .sql files and runs them; no migration_history table or checkpoint', 'simple_migrate.gleam: run_all_migrations() has no deduplication', 'Re-running migrations can cause errors from duplicate objects; no idempotency guarantee');
