// extension.js - AUTO-GENERATED by Gleam extension_generator!
// Generated: 2026-05-08 - DO NOT EDIT THIS FILE!

// Auto-generated by Gleam - DO NOT EDIT
import { Type } from "@sinclair/typebox";
import { execSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

import { get_resolved_identity } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/agent_identity.mjs";
import { add as task_add, complete as task_complete, list as task_list, get as task_get } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/task.mjs";
import { list as agents_list } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/agents.mjs";
import { add as issue_add, list as issue_list, resolve as issue_resolve } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/issue.mjs";
import { build as skill_build, list as skill_list, get as skill_get, search as skill_search } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/skill.mjs";
import { save as learn } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/learning.mjs";
import { send as broadcast_send, list as broadcast_list } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/broadcast.mjs";
import { create as meeting_create, list as meeting_list, get as meeting_get, add_opinion as meeting_add_opinion, list_opinions as meeting_list_opinions, complete as meeting_complete } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/meeting.mjs";
import { stats } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/stats.mjs";
import { validate as commit_validate } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/validation.mjs";
import { request as inter_review_request, list_reviews as inter_reviews, show as inter_review_show } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/inter_review.mjs";
function unwrapGleamResult(result) {
  if (!result) return { ok: false, error: 'null result' };
  const typeName = result.constructor?.name || '';
  if (typeName === 'Ok') return { ok: true, value: result['0'] };
  if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };
  return { ok: true, value: result };
}

export default function(pi) {
  // Get current agent ID
  pi.registerTool({
    name: "psypi-my-id",
    description: "Get current agent ID",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam agent_identity.get_resolved_identity
      return { content: [{ type: "text", text: "psypi-my-id - not yet connected to Gleam" }] };
    }
  });

  // Get partner/monitor ID
  pi.registerTool({
    name: "psypi-partner-id",
    description: "Get partner/monitor ID",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam agent_identity.get_resolved_identity
      return { content: [{ type: "text", text: "psypi-partner-id - not yet connected to Gleam" }] };
    }
  });

  // List all agents
  pi.registerTool({
    name: "psypi-agents",
    description: "List all agents",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam agents.list
      return { content: [{ type: "text", text: "psypi-agents - not yet connected to Gleam" }] };
    }
  });

  // Add a new task
  pi.registerTool({
    name: "psypi-task-add",
    description: "Add a new task",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam task.add
      return { content: [{ type: "text", text: "psypi-task-add - not yet connected to Gleam" }] };
    }
  });

  // Complete a task
  pi.registerTool({
    name: "psypi-task-complete",
    description: "Complete a task",
    parameters: { "taskId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam task.complete
      return { content: [{ type: "text", text: "psypi-task-complete - not yet connected to Gleam" }] };
    }
  });

  // List tasks
  pi.registerTool({
    name: "psypi-tasks",
    description: "List tasks",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam task.list
      return { content: [{ type: "text", text: "psypi-tasks - not yet connected to Gleam" }] };
    }
  });

  // Build a skill
  pi.registerTool({
    name: "psypi-skill-build",
    description: "Build a skill",
    parameters: { "name": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam skill.build
      return { content: [{ type: "text", text: "psypi-skill-build - not yet connected to Gleam" }] };
    }
  });

  // List skills
  pi.registerTool({
    name: "psypi-skill-list",
    description: "List skills",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam skill.list
      return { content: [{ type: "text", text: "psypi-skill-list - not yet connected to Gleam" }] };
    }
  });

  // Show skill
  pi.registerTool({
    name: "psypi-skill-show",
    description: "Show skill",
    parameters: { "name": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam skill.get
      return { content: [{ type: "text", text: "psypi-skill-show - not yet connected to Gleam" }] };
    }
  });

  // Search skills
  pi.registerTool({
    name: "psypi-skill-search",
    description: "Search skills",
    parameters: { "query": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam skill.search
      return { content: [{ type: "text", text: "psypi-skill-search - not yet connected to Gleam" }] };
    }
  });

  // Add an issue
  pi.registerTool({
    name: "psypi-issue-add",
    description: "Add an issue",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam issue.add
      return { content: [{ type: "text", text: "psypi-issue-add - not yet connected to Gleam" }] };
    }
  });

  // List issues
  pi.registerTool({
    name: "psypi-issue-list",
    description: "List issues",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam issue.list
      return { content: [{ type: "text", text: "psypi-issue-list - not yet connected to Gleam" }] };
    }
  });

  // Resolve issue
  pi.registerTool({
    name: "psypi-issue-resolve",
    description: "Resolve issue",
    parameters: { "issueId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam issue.resolve
      return { content: [{ type: "text", text: "psypi-issue-resolve - not yet connected to Gleam" }] };
    }
  });

  // Save learning
  pi.registerTool({
    name: "psypi-learn",
    description: "Save learning",
    parameters: { "content": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam learning.save
      return { content: [{ type: "text", text: "psypi-learn - not yet connected to Gleam" }] };
    }
  });

  // AI reflect
  pi.registerTool({
    name: "psypi-areflect",
    description: "AI reflect",
    parameters: { "content": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam learning.save
      return { content: [{ type: "text", text: "psypi-areflect - not yet connected to Gleam" }] };
    }
  });

  // Send broadcast
  pi.registerTool({
    name: "psypi-broadcast-send",
    description: "Send broadcast",
    parameters: { "message": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam broadcast.send
      return { content: [{ type: "text", text: "psypi-broadcast-send - not yet connected to Gleam" }] };
    }
  });

  // List broadcasts
  pi.registerTool({
    name: "psypi-broadcast-list",
    description: "List broadcasts",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam broadcast.list
      return { content: [{ type: "text", text: "psypi-broadcast-list - not yet connected to Gleam" }] };
    }
  });

  // Create meeting
  pi.registerTool({
    name: "psypi-meeting-create",
    description: "Create meeting",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam meeting.create
      return { content: [{ type: "text", text: "psypi-meeting-create - not yet connected to Gleam" }] };
    }
  });

  // List meetings
  pi.registerTool({
    name: "psypi-meeting-list",
    description: "List meetings",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam meeting.list
      return { content: [{ type: "text", text: "psypi-meeting-list - not yet connected to Gleam" }] };
    }
  });

  // Get meeting
  pi.registerTool({
    name: "psypi-meeting-get",
    description: "Get meeting",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam meeting.get
      return { content: [{ type: "text", text: "psypi-meeting-get - not yet connected to Gleam" }] };
    }
  });

  // Add opinion
  pi.registerTool({
    name: "psypi-meeting-add-opinion",
    description: "Add opinion",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam meeting.add_opinion
      return { content: [{ type: "text", text: "psypi-meeting-add-opinion - not yet connected to Gleam" }] };
    }
  });

  // List opinions
  pi.registerTool({
    name: "psypi-meeting-list-opinions",
    description: "List opinions",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam meeting.list_opinions
      return { content: [{ type: "text", text: "psypi-meeting-list-opinions - not yet connected to Gleam" }] };
    }
  });

  // Complete meeting
  pi.registerTool({
    name: "psypi-meeting-complete",
    description: "Complete meeting",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam meeting.complete
      return { content: [{ type: "text", text: "psypi-meeting-complete - not yet connected to Gleam" }] };
    }
  });

  // Get statistics
  pi.registerTool({
    name: "psypi-stats",
    description: "Get statistics",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam stats.stats
      return { content: [{ type: "text", text: "psypi-stats - not yet connected to Gleam" }] };
    }
  });

  // Validate commit
  pi.registerTool({
    name: "psypi-validate-commit",
    description: "Validate commit",
    parameters: { "message": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam validation.validate
      return { content: [{ type: "text", text: "psypi-validate-commit - not yet connected to Gleam" }] };
    }
  });

  // Commit with review
  pi.registerTool({
    name: "psypi-commit",
    description: "Commit with review",
    parameters: { "message": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam inter_review.request
      return { content: [{ type: "text", text: "psypi-commit - not yet connected to Gleam" }] };
    }
  });

  // Request review
  pi.registerTool({
    name: "psypi-inter-review-request",
    description: "Request review",
    parameters: { "taskId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam inter_review.request
      return { content: [{ type: "text", text: "psypi-inter-review-request - not yet connected to Gleam" }] };
    }
  });

  // List reviews
  pi.registerTool({
    name: "psypi-inter-reviews",
    description: "List reviews",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam inter_review.list_reviews
      return { content: [{ type: "text", text: "psypi-inter-reviews - not yet connected to Gleam" }] };
    }
  });

  // Show review
  pi.registerTool({
    name: "psypi-inter-review-show",
    description: "Show review",
    parameters: { "reviewId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      // TODO: Connect to Gleam inter_review.show
      return { content: [{ type: "text", text: "psypi-inter-review-show - not yet connected to Gleam" }] };
    }
  });

}
