// extension.js - AUTO-GENERATED by Gleam extension_generator!
// Generated: 2026-05-08 - DO NOT EDIT THIS FILE!

// Auto-generated by Gleam - DO NOT EDIT
import { Type } from "@sinclair/typebox";
import { execSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

import { get_resolved_identity } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/agent_identity.mjs";
import { add as task_add, complete as task_complete, list as task_list, get as task_get } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/task.mjs";
import { list as agents_list } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/agents.mjs";
import { add as issue_add, list as issue_list, resolve as issue_resolve } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/issue.mjs";
import { build as skill_build, list as skill_list, get as skill_get, search as skill_search } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/skill.mjs";
import { save as learn } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/learning.mjs";
import { send as broadcast_send, list as broadcast_list } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/broadcast.mjs";
import { create as meeting_create, list as meeting_list, get as meeting_get, add_opinion as meeting_add_opinion, list_opinions as meeting_list_opinions, complete as meeting_complete } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/meeting.mjs";
import { stats } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/stats.mjs";
import { validate as commit_validate } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/validation.mjs";
import { request as inter_review_request, list_reviews as inter_reviews, show as inter_review_show } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/inter_review.mjs";
function unwrapGleamResult(result) {
  if (!result) return { ok: false, error: 'null result' };
  const typeName = result.constructor?.name || '';
  if (typeName === 'Ok') return { ok: true, value: result['0'] };
  if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };
  return { ok: true, value: result };
}

async function getIdentity(permanent = false, ctx) {
  const sessionId = ctx?.sessionManager?.getSessionId() || '';
  const source = process.env.PSYPI_AGENT_SOURCE || 'psypi';
  const project = 'psypi';
  let gitHash = '';
  try { const { execSync } = await import('child_process');
    gitHash = execSync('git rev-parse HEAD', { cwd: process.cwd() }).toString().trim(); } catch {}
  const machineFingerprint = process.env.HOSTNAME || process.env.COMPUTERNAME || 'unknown';
  const model = ctx?.model?.id || process.env.PSYPI_MODEL || '';
  // Call Gleam with all 7 args!
  const result = await get_resolved_identity(permanent, sessionId, project, gitHash, machineFingerprint, source, model);
  return unwrapGleamResult(result);
}

export default function(pi) {
  // Get current agent ID
  pi.registerTool({
    name: "psypi-my-id",
    description: "Get current agent ID",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await getIdentity(false, _ctx);
      return result.ok ? { content: [{ type: "text", text: result.value.id }] } : { content: [{ type: "text", text: `Error: ${result.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Get partner/monitor ID
  pi.registerTool({
    name: "psypi-partner-id",
    description: "Get partner/monitor ID",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await getIdentity(true, _ctx);
      return result.ok ? { content: [{ type: "text", text: result.value.id }] } : { content: [{ type: "text", text: `Error: ${result.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List all agents
  pi.registerTool({
    name: "psypi-agents",
    description: "List all agents",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await agents_list();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Add a new task
  pi.registerTool({
    name: "psypi-task-add",
    description: "Add a new task",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await task_add(params.title, params.description || "", params.priority || 5, "cli");
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: `Task: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Complete a task
  pi.registerTool({
    name: "psypi-task-complete",
    description: "Complete a task",
    parameters: { "taskId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await task_complete(params.taskId);
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: `Completed!` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List tasks
  pi.registerTool({
    name: "psypi-tasks",
    description: "List tasks",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await task_list(params?.status || null);
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Build a skill
  pi.registerTool({
    name: "psypi-skill-build",
    description: "Build a skill",
    parameters: { "name": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await build();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List skills
  pi.registerTool({
    name: "psypi-skill-list",
    description: "List skills",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await list();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Show skill
  pi.registerTool({
    name: "psypi-skill-show",
    description: "Show skill",
    parameters: { "name": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await get();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Search skills
  pi.registerTool({
    name: "psypi-skill-search",
    description: "Search skills",
    parameters: { "query": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await search();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Add an issue
  pi.registerTool({
    name: "psypi-issue-add",
    description: "Add an issue",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await add();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List issues
  pi.registerTool({
    name: "psypi-issue-list",
    description: "List issues",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await list();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Resolve issue
  pi.registerTool({
    name: "psypi-issue-resolve",
    description: "Resolve issue",
    parameters: { "issueId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await resolve();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Save learning
  pi.registerTool({
    name: "psypi-learn",
    description: "Save learning",
    parameters: { "content": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await save();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // AI reflect
  pi.registerTool({
    name: "psypi-areflect",
    description: "AI reflect",
    parameters: { "content": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await save();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Send broadcast
  pi.registerTool({
    name: "psypi-broadcast-send",
    description: "Send broadcast",
    parameters: { "message": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await send();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List broadcasts
  pi.registerTool({
    name: "psypi-broadcast-list",
    description: "List broadcasts",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await list();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Create meeting
  pi.registerTool({
    name: "psypi-meeting-create",
    description: "Create meeting",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await create();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List meetings
  pi.registerTool({
    name: "psypi-meeting-list",
    description: "List meetings",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await list();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Get meeting
  pi.registerTool({
    name: "psypi-meeting-get",
    description: "Get meeting",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await get();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Add opinion
  pi.registerTool({
    name: "psypi-meeting-add-opinion",
    description: "Add opinion",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await add_opinion();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List opinions
  pi.registerTool({
    name: "psypi-meeting-list-opinions",
    description: "List opinions",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await list_opinions();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Complete meeting
  pi.registerTool({
    name: "psypi-meeting-complete",
    description: "Complete meeting",
    parameters: { "meetingId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await complete();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Get statistics
  pi.registerTool({
    name: "psypi-stats",
    description: "Get statistics",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await stats();
      const r = unwrapGleamResult(result);
      const s = r.value;
      return r.ok ? { content: [{ type: "text", text: `Tasks:${s.tasks} Issues:${s.issues} Skills:${s.skills} Meetings:${s.meetings}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Validate commit
  pi.registerTool({
    name: "psypi-validate-commit",
    description: "Validate commit",
    parameters: { "message": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await validate();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Commit with review
  pi.registerTool({
    name: "psypi-commit",
    description: "Commit with review",
    parameters: { "message": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await request();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Request review
  pi.registerTool({
    name: "psypi-inter-review-request",
    description: "Request review",
    parameters: { "taskId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await request();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List reviews
  pi.registerTool({
    name: "psypi-inter-reviews",
    description: "List reviews",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await list_reviews();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Show review
  pi.registerTool({
    name: "psypi-inter-review-show",
    description: "Show review",
    parameters: { "reviewId": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try { const result = await show();
      const r = unwrapGleamResult(result);
      return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] }; } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

}
