// extension.js - Generated by Gleam extension_generator
// DO NOT EDIT - Regenerate with: gleam run -m psypi_cli/extension_generator

import { get_resolved_identity } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/agent_identity.mjs";
import { add } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/task.mjs";
import { list } from "../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/task.mjs";


export default function(pi) {
  function unwrapGleamResult(result) {
    if (!result) return { ok: false, error: 'null result' };
    const typeName = result.constructor?.name || '';
    if (typeName === 'Ok') return { ok: true, value: result['0'] };
    if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };
    return { ok: true, value: result };
  }

  // Session ID — obtained once at session start, never exposed again
  let _sessionId = null;
  pi.on('session_start', async (_event, ctx) => {
    _sessionId = ctx.sessionManager.getSessionId() || '';
  });

  // Get current agent ID
  pi.registerTool({
    name: "psypi-my-id",
    description: "Get current agent ID",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try {
        const result = await get_resolved_identity(false, _sessionId, "psypi", "", "", "psypi", "");
        const r = unwrapGleamResult(result);
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Get partner/monitor ID (permanent identity)
  pi.registerTool({
    name: "psypi-partner-id",
    description: "Get partner/monitor ID (permanent identity)",
    parameters: {},
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try {
        const result = await get_resolved_identity(true, "", "psypi", "", "", "psypi", "");
        const r = unwrapGleamResult(result);
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // Add a new task
  pi.registerTool({
    name: "psypi-task-add",
    description: "Add a new task",
    parameters: { "title": { type: "string" } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try {
        const result = await add(params.title || "", "", 5, "cli");
        const r = unwrapGleamResult(result);
        return r.ok ? { content: [{ type: "text", text: `Task: ${r.value}` }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

  // List tasks, optionally filtered by status
  pi.registerTool({
    name: "psypi-tasks",
    description: "List tasks, optionally filtered by status",
    parameters: { "status": { type: "string", optional: true } },
    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
      try {
        const result = await list(params?.status || null);
        const r = unwrapGleamResult(result);
        return r.ok ? { content: [{ type: "text", text: JSON.stringify(r.value) }] } : { content: [{ type: "text", text: `Error: ${r.error}` }] };
      } catch(e) { return { content: [{ type: "text", text: `Error: ${e.message}` }] }; }
    }
  });

}
