// extension_generator.gleam — Pi Extension Generator
//
// Design:
//   - Each Gleam module exports PiToolCall values (e.g., agent_identity.my_id_tool())
//   - The generator COLLECTS these values and composes them into extension.js
//   - Everything is TEXT — Gleam writes JS source code as strings
//
// Two sources of JS text:
//   1. PiToolCall.to_js_text() → pi.registerTool({...}) blocks
//   2. PiToolCall.to_import_line() → import { fn } from "path.mjs"
//
// The generator is a COOK: it gathers ingredients (PiToolCall values),
// prepares them (converts to JS text), and assembles the final dish (extension.js).

import gleam/io
import gleam/list
import gleam/string
import psypi_cli/pi_tool_call.{type PiToolCall, to_js_text, to_import_line}
import psypi_cli/agent_identity.{my_id_tool, partner_id_tool}
import psypi_cli/task.{task_add_tool, task_list_tool}
import psypi_cli/file_utils.{write_file}


pub fn write_extension() -> Nil {
  let extension_path = "../../src/agent/extension/extension.js"
  // IMPORTANT: Always call generate() — never compose text here.
  // Having two composition paths caused the "pi is not defined" bug.
  let content = generate()
  case write_file(extension_path, content) {
    Ok(_) -> Nil
    Error(e) -> io.println("Error writing extension.js: " <> string.inspect(e))
  }
}

// -------------------------------------------------------------------
// Tool registry — the SINGLE place where all Pi tools are listed
// To add a new tool:
//   1. Define a PiToolCall value in its Gleam module
//   2. Import it here
//   3. Add it to the list below
// -------------------------------------------------------------------

pub fn all_tools() -> List(PiToolCall) {
  [
    my_id_tool(),
    partner_id_tool(),
    task_add_tool(),
    task_list_tool(),
  ]
}

// -------------------------------------------------------------------
// JS text composition
// -------------------------------------------------------------------

fn imports_text(tools: List(PiToolCall)) -> String {
  let header =
    [
      "// extension.js - Generated by Gleam extension_generator",
      "// DO NOT EDIT - Regenerate with: gleam run -m psypi_cli/extension_generator",
      "",
    ]
    |> list.map(fn(s) { s <> "\n" })
    |> string.concat

  let lines =
    tools
    |> list.map(to_import_line)
    |> list.unique
    |> list.map(fn(line) { line <> "\n" })
    |> string.concat

  header <> lines <> "\n"
}

fn helpers_text() -> String {
  [
    "  function unwrapGleamResult(result) {",
    "    if (!result) return { ok: false, error: 'null result' };",
    "    const typeName = result.constructor?.name || '';",
    "    if (typeName === 'Ok') return { ok: true, value: result['0'] };",
    "    if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };",
    "    return { ok: true, value: result };",
    "  }",
    "",
    "  // Session ID — obtained once at session start, never exposed again",
    "  let _sessionId = null;",
    "  pi.on('session_start', async (_event, ctx) => {",
    "    _sessionId = ctx.sessionManager.getSessionId() || '';",
    "  });",
    "",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

fn tools_text(tools: List(PiToolCall)) -> String {
  tools
  |> list.map(to_js_text)
  |> string.concat
}

pub fn generate() -> String {
  let tools = all_tools()
  imports_text(tools)
  <> "\nexport default function(pi) {\n"
  <> helpers_text()
  <> tools_text(tools)
  <> "}\n"
}

pub fn main() {
  // Print to stdout (for debugging)
  generate() |> io.print
  // Also write to extension.js
  write_extension()
}
