// extension_generator.gleam - Metaprogramming: Gleam generates extension.js!
// This is the Lisp way - programs that write programs!

import gleam/io
import gleam/string
import gleam/list

pub type ToolDef {
  ToolDef(
    name: String,
    module: String,
    function: String,
    description: String,
    params: String,
  )
}

fn no_params() -> String { "{}" }
fn p_string(name: String) -> String { "{ \"" <> name <> "\": { type: \"string\" } }" }
fn p_opt_string(name: String) -> String { "{ \"" <> name <> "\": { type: \"string\", optional: true } }" }

pub fn all_tools() -> List(ToolDef) {
  [
    ToolDef("psypi-my-id", "agent_identity", "get_resolved_identity", "Get current agent ID", no_params()),
    ToolDef("psypi-partner-id", "agent_identity", "get_resolved_identity", "Get partner/monitor ID", no_params()),
    ToolDef("psypi-agents", "agents", "list", "List all agents", no_params()),
    ToolDef("psypi-task-add", "task", "add", "Add a new task", p_string("title")),
    ToolDef("psypi-task-complete", "task", "complete", "Complete a task", p_string("taskId")),
    ToolDef("psypi-tasks", "task", "list", "List tasks", p_opt_string("status")),
    ToolDef("psypi-skill-build", "skill", "build", "Build a skill", p_string("name")),
    ToolDef("psypi-skill-list", "skill", "list", "List skills", no_params()),
    ToolDef("psypi-skill-show", "skill", "get", "Show skill", p_string("name")),
    ToolDef("psypi-skill-search", "skill", "search", "Search skills", p_string("query")),
    ToolDef("psypi-issue-add", "issue", "add", "Add an issue", p_string("title")),
    ToolDef("psypi-issue-list", "issue", "list", "List issues", p_opt_string("status")),
    ToolDef("psypi-issue-resolve", "issue", "resolve", "Resolve issue", p_string("issueId")),
    ToolDef("psypi-learn", "learning", "save", "Save learning", p_string("content")),
    ToolDef("psypi-areflect", "learning", "save", "AI reflect", p_string("content")),
    ToolDef("psypi-broadcast-send", "broadcast", "send", "Send broadcast", p_string("message")),
    ToolDef("psypi-broadcast-list", "broadcast", "list", "List broadcasts", no_params()),
    ToolDef("psypi-meeting-create", "meeting", "create", "Create meeting", p_string("title")),
    ToolDef("psypi-meeting-list", "meeting", "list", "List meetings", p_opt_string("status")),
    ToolDef("psypi-meeting-get", "meeting", "get", "Get meeting", p_string("meetingId")),
    ToolDef("psypi-meeting-add-opinion", "meeting", "add_opinion", "Add opinion", p_string("meetingId")),
    ToolDef("psypi-meeting-list-opinions", "meeting", "list_opinions", "List opinions", p_string("meetingId")),
    ToolDef("psypi-meeting-complete", "meeting", "complete", "Complete meeting", p_string("meetingId")),
    ToolDef("psypi-stats", "stats", "stats", "Get statistics", no_params()),
    ToolDef("psypi-validate-commit", "validation", "validate", "Validate commit", p_string("message")),
    ToolDef("psypi-commit", "inter_review", "request", "Commit with review", p_string("message")),
    ToolDef("psypi-inter-review-request", "inter_review", "request", "Request review", p_string("taskId")),
    ToolDef("psypi-inter-reviews", "inter_review", "list_reviews", "List reviews", p_opt_string("status")),
    ToolDef("psypi-inter-review-show", "inter_review", "show", "Show review", p_string("reviewId")),
  ]
}

fn import_line(module: String, aliases: String) -> String {
  "import { " <> aliases <> " } from \"../../../gleam/psypi_core/build/dev/javascript/psypi_core/psypi_cli/" <> module <> ".mjs\";"
}

pub fn generate_imports() -> String {
  "// Auto-generated by Gleam - DO NOT EDIT\n"
  <> "import { Type } from \"@sinclair/typebox\";\n"
  <> "import { execSync } from \"child_process\";\n"
  <> "import path from \"path\";\n"
  <> "import { fileURLToPath } from \"url\";\n\n"
  <> import_line("agent_identity", "get_resolved_identity") <> "\n"
  <> import_line("task", "add as task_add, complete as task_complete, list as task_list, get as task_get") <> "\n"
  <> import_line("agents", "list as agents_list") <> "\n"
  <> import_line("issue", "add as issue_add, list as issue_list, resolve as issue_resolve") <> "\n"
  <> import_line("skill", "build as skill_build, list as skill_list, get as skill_get, search as skill_search") <> "\n"
  <> import_line("learning", "save as learn") <> "\n"
  <> import_line("broadcast", "send as broadcast_send, list as broadcast_list") <> "\n"
  <> import_line("meeting", "create as meeting_create, list as meeting_list, get as meeting_get, add_opinion as meeting_add_opinion, list_opinions as meeting_list_opinions, complete as meeting_complete") <> "\n"
  <> import_line("stats", "stats") <> "\n"
  <> import_line("validation", "validate as commit_validate") <> "\n"
  <> import_line("inter_review", "request as inter_review_request, list_reviews as inter_reviews, show as inter_review_show") <> "\n"
}

pub fn generate_helpers() -> String {
  "function unwrapGleamResult(result) {\n"
  <> "  if (!result) return { ok: false, error: 'null result' };\n"
  <> "  const typeName = result.constructor?.name || '';\n"
  <> "  if (typeName === 'Ok') return { ok: true, value: result['0'] };\n"
  <> "  if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };\n"
  <> "  return { ok: true, value: result };\n"
  <> "}\n\n"
}

pub fn generate_tool_call(tool: ToolDef) -> String {
  "  // " <> tool.description <> "\n"
  <> "  pi.registerTool({\n"
  <> "    name: \"" <> tool.name <> "\",\n"
  <> "    description: \"" <> tool.description <> "\",\n"
  <> "    parameters: " <> tool.params <> ",\n"
  <> "    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {\n"
  <> "      // TODO: Connect to Gleam " <> tool.module <> "." <> tool.function <> "\n"
  <> "      return { content: [{ type: \"text\", text: \"" <> tool.name <> " - not yet connected to Gleam\" }] };\n"
  <> "    }\n"
  <> "  });\n\n"
}

pub fn generate_tools_section() -> String {
  all_tools() |> list.map(generate_tool_call) |> string.concat
}

pub fn generate() -> String {
  "// extension.js - AUTO-GENERATED by Gleam extension_generator!\n"
  <> "// Generated: 2026-05-08 - DO NOT EDIT THIS FILE!\n\n"
  <> generate_imports()
  <> generate_helpers()
  <> "export default function(pi) {\n"
  <> generate_tools_section()
  <> "}\n"
}

pub fn main() {
  generate() |> io.print
}