// extension_generator.gleam — Pi Extension Generator
// Composes small generator modules into extension.js

import agent_identity.{autonomic_id_tool, somatic_id_tool}
import agents.{agents_list_tool}
import areflect.{areflect_tool}
import broadcast.{broadcast_list_tool, broadcast_send_tool}
import code_version.{doc_list_tool, doc_save_tool}
import directive.{clear_directives_tool, direct_worker_tool}
import event_hooks.{list_active_hooks_tool, list_hooks_tool}
import file_utils.{write_file}
import filepath
import gleam/io
import gleam/list
import gleam/string
import issue_tools.{issue_add_tool, issue_list_tool, issue_count_tool, issue_get_tool, issue_resolve_tool}
import learning.{learn_save_tool}
import meeting.{meeting_create_tool, meeting_get_tool, meeting_list_tool, meeting_opinions_tool}
import memory.{memory_search_tool}
import monitor_ai.{monitor_alerts_tool, monitor_health_tool, monitor_stats_tool, monitor_status_tool, monitor_suggest_tool, autonomic_listen_command, autonomic_reload_command}

import pi_tool_call.{type PiToolCall, type PiEventHook, type PiCommandReg, command_to_js, event_hook, event_hook_to_js, to_import_line, to_js_text}
import skill.{skill_get_tool, skill_list_tool, skill_search_tool}
import stats.{stats_show_tool}
import task.{task_add_tool, task_complete_tool, task_list_tool}

// Generator modules
import generator/tool_call
import hook_before_agent_start
import generator/session_start
import generator/model_select
import generator/tool_result
import generator/agent_lifecycle

// ---------------------------------------------------------------------------
// Tool registry
// ---------------------------------------------------------------------------

pub fn all_tools() -> List(PiToolCall) {
  [
    // Identity
    somatic_id_tool(),
    autonomic_id_tool(),
    // Tasks
    task_add_tool(),
    task_list_tool(),
    task_complete_tool(),
    // Stats
    stats_show_tool(),
    // Code versioning
    doc_save_tool(),
    doc_list_tool(),
    // Issues
    issue_add_tool(),
    issue_list_tool(),
    issue_count_tool(),
    issue_get_tool(),
    issue_resolve_tool(),
    // Skills
    skill_list_tool(),
    skill_get_tool(),
    skill_search_tool(),
    // Meetings
    meeting_list_tool(),
    meeting_get_tool(),
    meeting_opinions_tool(),
    meeting_create_tool(),
    // Learning
    learn_save_tool(),
    // Memory
    memory_search_tool(),
    // Broadcast
    broadcast_send_tool(),
    broadcast_list_tool(),
    // Reflection
    areflect_tool(),
    // Agents
    agents_list_tool(),
    // Monitor
    monitor_status_tool(),
    monitor_health_tool(),
    monitor_alerts_tool(),
    monitor_stats_tool(),
    monitor_suggest_tool(),
    // Event hooks
    list_hooks_tool(),
    list_active_hooks_tool(),
    // Directives (Autonomic → Somatic communication)
    direct_worker_tool(),
    clear_directives_tool(),
  ]
}

// ---------------------------------------------------------------------------
// Event hooks registry
// ---------------------------------------------------------------------------

pub fn all_event_hooks() -> List(PiEventHook) {
  [
    event_hook("tool_call", tool_call.handler_body()),
    event_hook("session_start", session_start.handler_body()),
    event_hook("model_select", model_select.handler_body()),
    event_hook("before_agent_start", hook_before_agent_start.handler_body()),
    event_hook("agent_start", agent_lifecycle.start_body()),
    event_hook("agent_end", agent_lifecycle.end_body()),
    event_hook("tool_result", tool_result.handler_body()),
  ]
}

// ---------------------------------------------------------------------------
// Commands registry
// ---------------------------------------------------------------------------

pub fn all_commands() -> List(PiCommandReg) {
  [
    // Monitor commands (from monitor_ai module)
    autonomic_listen_command(),
    autonomic_reload_command()
  ]
}

// ---------------------------------------------------------------------------
// JS text composition
// ---------------------------------------------------------------------------

fn imports_text(tools: List(PiToolCall)) -> String {
  let header = [
    "// extension.js - Generated by Gleam extension_generator",
    "// DO NOT EDIT - Regenerate with: gleam run -m extension_generator",
    "",
    "import { complete, getModel } from \"@mariozechner/pi-ai\";",
    "import { notify_error as pi_extension_notify_error } from \"./build/dev/javascript/psypi/pi_extension.mjs\";",
    "",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat

  let lines =
    tools
    |> list.map(to_import_line)
    |> list.unique
    |> list.map(fn(line) { line <> "\n" })
    |> string.concat

  header <> lines <> "\n"
}

fn helpers_text() -> String {
  [
    "  function unwrapGleamResult(result) {",
    "    if (!result) return { ok: false, error: 'null result' };",
    "    const typeName = result.constructor?.name || '';",
    "    if (typeName === 'Ok') return { ok: true, value: result['0'] };",
    "    if (typeName === 'Error') return { ok: false, error: result['0']?.['0'] || result['0']?.toString() || 'Unknown' };",
    "    return { ok: true, value: result };",
    "  }",
    "",
    "  // Session ID — obtained once at session start, never exposed again",
    "  let _sessionId = null;",
    "  pi.on('session_start', async (_event, ctx) => {",
    "    _sessionId = ctx.sessionManager.getSessionId() || '';",
    "  });",
    "",
    "  // Monitor LLM call helper",
    "  async function callMonitor(ctx, messages, systemPrompt) {",
    "    if (!ctx.model) throw new Error('No model available');",
    "    const auth = await ctx.modelRegistry.getApiKeyAndHeaders(ctx.model);",
    "    if (!auth.ok || !auth.apiKey) throw new Error(auth.error || 'No API key');",
    "    const availableTools = pi.getActiveTools().join(', ');",
    "    const fullPrompt = systemPrompt + '\\n\\nAVAILABLE TOOLS: ' + availableTools + '\\nYou have full access to these tools.';",
    "    const response = await complete(",
    "      ctx.model,",
    "      { systemPrompt: fullPrompt, messages },",
    "      { apiKey: auth.apiKey, headers: auth.headers }",
    "    );",
    "    return response.content",
    "      .filter(c => c.type === 'text')",
    "      .map(c => c.text)",
    "      .join('\\n');",
    "  }",
    "",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

fn tools_text(tools: List(PiToolCall)) -> String {
  tools
  |> list.map(to_js_text)
  |> string.concat
}

fn commands_text(commands: List(PiCommandReg)) -> String {
  commands
  |> list.map(command_to_js)
  |> string.concat
}

fn event_hooks_text(hooks: List(PiEventHook)) -> String {
  hooks
  |> list.map(event_hook_to_js)
  |> string.concat
}

// ---------------------------------------------------------------------------
// Main generation
// ---------------------------------------------------------------------------

pub fn generate() -> String {
  let tools = all_tools()
  let hooks = all_event_hooks()
  let commands = all_commands()
  imports_text(tools)
  <> "\nexport default function(pi) {\n"
  <> helpers_text()
  <> message_renderer_text()
  <> event_hooks_text(hooks)
  <> tools_text(tools)
  <> commands_text(commands)
  <> monitor_consult_tool()
  <> psypi_commit_tool()
  <> "}\n"
}

fn message_renderer_text() -> String {
  [
    "  // Register custom renderer for A-worker (autonomic) wake-up messages\n",
    "  pi.registerMessageRenderer('autonomic-wakeup', (message, options, theme) => {\n",
    "    const { expanded } = options;\n",
    "    let text = theme.fg('accent', '[A-worker] ');\n",
    "    text += theme.fg('warning', message.content);\n",
    "    if (expanded && message.details) {\n",
    "      text += '\\n' + theme.fg('dim', JSON.stringify(message.details, null, 2));\n",
    "    }\n",
    "    return new Text(text, 0, 0);\n",
    "  });\n",
    "\n",
  ]
  |> list.map(fn(s) { s })
  |> string.concat
}

fn monitor_consult_tool() -> String {
  [
    "  // psypi-consult-autonomic - S-worker consults A-worker for advice\n",
    "  pi.registerTool({\n",
    "    name: 'psypi-consult-autonomic',\n",
    "    description: 'Consult the Autonomic Worker for difficult decisions. Only the Somatic Worker should use this.',\n",
    "    parameters: { \"type\": \"object\",\n    \"properties\": {\n      \"question\": { \"type\": \"string\" }\n    },\n    \"required\": [\"question\"]\n  },\n",
    "    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {\n",
    "      try {\n",
    "        const question = params.question || 'What should I consider?';\n",
    "        const systemPrompt = `You are Monitor, a senior technical advisor. Provide concise, actionable advice. Consider: safety, quality, architecture, trade-offs.`;\n",
    "        const messages = [{ role: 'user', content: [{ type: 'text', text: question }], timestamp: Date.now() }];\n",
    "        const response = await callMonitor(ctx, messages, systemPrompt);\n",
    "        const marked = '[Autonomic] ' + response;\n",
    "        ctx.ui.notify(marked, 'info');\n",
    "        return { content: [{ type: 'text', text: marked }] };\n",
    "      } catch(e) { return { content: [{ type: 'text', text: 'Autonomic error: ' + (e.message || 'unknown') }] }; }\n",
    "    }\n",
    "  });\n",
    "\n",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

fn psypi_commit_tool() -> String {
  [
    "  // psypi-commit - Inter-review with Monitor",
    "  pi.registerTool({",
    "    name: 'psypi-commit',",
    "    description: 'Commit with Monitor inter-review.',",
    "    parameters: { \"type\": \"object\",\n    \"properties\": {\n      \"message\": { \"type\": \"string\" },\n      \"review_id\": { \"type\": \"string\" }\n    },\n    \"required\": [\"message\"]\n  },",
    "    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {",
    "      try {",
    "        const { execSync } = await import('child_process');",
    "        const message = params.message || 'No commit message';",
    "        const reviewId = params.review_id || '';",
    "",
    "        if (reviewId) {",
    "          const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;",
    "          if (!uuidRegex.test(reviewId)) { return { content: [{ type: 'text', text: 'Invalid review_id format.' }] }; }",
    "          try { execSync('git add -A && git commit -m \"' + message.replace(/\"/g, '\\\\\"') + '\"', { encoding: 'utf8' }); }",
    "          catch(e) { return { content: [{ type: 'text', text: 'Commit failed: ' + e.message }] }; }",
    "          return { content: [{ type: 'text', text: '✅ Committed: ' + message }] };",
    "        }",
    "",
    "        let changedFiles = '';",
    "        let diff = '';",
    "        try {",
    "          changedFiles = execSync('git diff --name-only', { encoding: 'utf8' });",
    "          diff = execSync('git diff', { encoding: 'utf8', maxBuffer: 10*1024*1024 });",
    "        } catch(e) { return { content: [{ type: 'text', text: 'Error getting git diff: ' + e.message }] }; }",
    "",
    "        const context = `CHANGES:\\nFiles: ${changedFiles}\\n---\\nDIFF:\\n${diff.substring(0, 8000)}\\n---\\nCOMMIT MESSAGE: ${message}\\n---\\nREVIEW: Assess code quality, safety, and fit. Respond: PASS or FAIL, SCORE/100, FEEDBACK.`;",
    "",
    "        const systemPrompt = 'You are Monitor. Review code. Be thorough but fair.';",
    "        const messages = [{ role: 'user', content: [{ type: 'text', text: context }], timestamp: Date.now() }];",
    "        const response = await callMonitor(ctx, messages, systemPrompt);",
    "",
    "        const passMatch = response.match(/PASS/i);",
    "        const scoreMatch = response.match(/SCORE.?(\\d+)/i);",
    "        const score = scoreMatch ? parseInt(scoreMatch[1]) : 0;",
    "        const isPass = passMatch && score >= 70;",
    "",
    "        if (!isPass) {",
    "          return { content: [{ type: 'text', text: 'Review: ' + response + '\\n\\n❌ Score ' + score + '/100 - Need improvements. Fix and run psypi-commit again.' }] };",
    "        }",
    "",
    "        const newReviewId = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {",
    "          const r = Math.random() * 16 | 0;",
    "          const v = c === 'x' ? r : (r & 0x3 | 0x8);",
    "          return v.toString(16);",
    "        });",
    "",
    "        return { content: [{ type: 'text', text: '✅ Review PASSED (' + score + '/100)\\n📋 review_id: ' + newReviewId + '\\n\\nTo commit: psypi-commit --review-id=' + newReviewId + ' \"' + message + '\"' }] };",
    "      } catch(e) { return { content: [{ type: 'text', text: 'Error: ' + e.message }] }; }",
    "    }",
    "  });",
    "",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

pub fn write_extension() -> Nil {
  let project_root = get_project_root()
  let extension_path = filepath.join(project_root, "extension.js")
  let content = generate()
  case write_file(extension_path, content) {
    Ok(_) -> Nil
    Error(e) -> io.println("Error writing extension.js: " <> string.inspect(e))
  }
}

pub fn main() {
  generate() |> io.print
  write_extension()
}

@external(javascript, "./node_ffi.mjs", "get_project_root")
pub fn get_project_root() -> String
