// ppi_gen.gleam - Generates bin/ppi.mjs and extension.js
// Run with: gleam run -m ppi_gen
//
// This module generates two JS files:
//   1. bin/ppi.mjs  — Node.js entry point (imports Gleam generator, spawns Pi)
//   2. extension.js — Pi extension (tools, hooks, commands)
//
// After generation, run: node bin/ppi.mjs [args]

import extension_generator
import file_utils.{write_file}
import filepath
import gleam/io
import gleam/list
import gleam/string

@external(javascript, "./node_ffi.mjs", "get_project_root")
pub fn get_project_root() -> String

pub fn main() {
  write_ppi_entry()
  extension_generator.write_extension()
  io.println("[ppi_gen] Generated bin/ppi.mjs and extension.js")
}

// ---------------------------------------------------------------------------
// bin/ppi.mjs generation
// ---------------------------------------------------------------------------

pub fn generate_ppi_entry() -> String {
  let lines = [
    "#!/usr/bin/env node",
    "// bin/ppi.mjs — Generated by ppi_gen.gleam",
    "// DO NOT EDIT — Regenerate with: gleam run -m ppi_gen",
    "",
    "import { spawn } from 'child_process';",
    "import { fileURLToPath } from 'url';",
    "import { dirname, join, resolve } from 'path';",
    "import { writeFileSync, realpathSync, readFileSync, mkdirSync } from 'fs';",
    "import { homedir } from 'os';",
    "",
    "const __filename = fileURLToPath(import.meta.url);",
    "const __dirname = dirname(realpathSync(__filename));",
    "const projectDir = resolve(__dirname, '..');",
    "",
    "const { generate } = await import(",
    "  join(projectDir, 'build/dev/javascript/psypi/extension_generator.mjs')",
    ");",
    "",
    "const extensionPath = join(projectDir, 'extension.js');",
    "writeFileSync(extensionPath, generate(), 'utf8');",
    "",
    "const piBin = 'pi';",
    "let args = process.argv.slice(2);",
    "let minimal = false;",
    "if (args.includes('--minimal')) {",
    "  minimal = true;",
    "  args = args.filter(a => a !== '--minimal');",
    "}",
    "",
    persist_settings_text(),
    "",
    "const piArgs = ['-e', extensionPath, ...args];",
    "",
    "if (minimal) {",
    "  piArgs.unshift(",
    "    '--no-session', '--no-skills', '--no-context-files',",
    "    '--tools', 'read,bash,psypi-somatic-id,psypi-autonomic-id'",
    "  );",
    "}",
    "",
    "const child = spawn(piBin, piArgs, {",
    "  stdio: 'inherit',",
    "  shell: false,",
    "  cwd: process.cwd()",
    "});",
    "",
    "child.on('close', code => process.exit(code || 0));",
    "child.on('error', err => {",
    "  console.error('Failed to start Pi:', err.message);",
    "  process.exit(1);",
    "});",
    "",
  ]
  lines
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

fn persist_settings_text() -> String {
  [
    "const settingsDir = join(homedir(), '.pi', 'agent');",
    "const settingsPath = join(settingsDir, 'settings.json');",
    "try { mkdirSync(settingsDir, { recursive: true }); } catch (_) {}",
    "let settings = {};",
    "try { settings = JSON.parse(readFileSync(settingsPath, 'utf8')); } catch (_) {}",
    "settings.psypiMode = minimal ? 'minimal' : 'normal';",
    "writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf8');",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

pub fn write_ppi_entry() -> Nil {
  let project_root = get_project_root()
  let ppi_path = filepath.join(project_root, "bin/ppi.mjs")
  let content = generate_ppi_entry()
  case write_file(ppi_path, content) {
    Ok(_) -> Nil
    Error(e) ->
      io.println("Error writing bin/ppi.mjs: " <> string.inspect(e))
  }
}
