// pi_tool_call.gleam — Pi Tool Call type
//
// Design:
//   - Each Gleam module that wants to expose a Pi tool defines a PiToolCall value
//   - PiToolCall carries ALL metadata required by Pi Extension API
//   - The generator collects PiToolCall values and composes them into extension.js
//   - Everything is TEXT — Gleam writes JS source code, not JS objects
//
// Pi Extension API requires:
//   1. pi.registerTool({ name, description, parameters, execute })
//   2. execute returns { content: [{ type: "text", text: "..." }] }
//   3. Import the Gleam-compiled .mjs module

import gleam/list
import gleam/string

// -------------------------------------------------------------------
// Types
// -------------------------------------------------------------------

/// How to format the tool result
pub type ResultFormat {
  /// JSON.stringify the result
  RawJson
  /// Template string, e.g. "Task: ${r.value}"
  Template(String)
  /// Custom JS expression that produces the text
  CustomJs(String)
}

/// A parameter for the Pi tool (maps to TypeBox schema)
pub type PiParam {
  PiParam(name: String, param_type: String, required: Bool)
}

/// Argument to pass to the Gleam function call
pub type FnArg {
  /// Literal JS expression, e.g. "false", "\"psypi\"", "_sessionId"
  JsLiteral(String)
  /// Read from Pi tool params, e.g. "params.title || \"\""
  FromParam(String)
}

/// Complete definition of one Pi tool
pub type PiToolCall {
  PiToolCall(
    // Pi tool identity
    name: String,
    description: String,
    // Pi parameters schema (JS text for TypeBox)
    params: List(PiParam),
    // Which Gleam module/function to call
    module: String,
    fn_name: String,
    // Arguments to pass to the Gleam function
    args: List(FnArg),
    // How to format the result
    result_format: ResultFormat,
  )
}

/// A Pi event hook — intercepts Pi lifecycle events.
/// The handler body is JS text generated by a Gleam function.
pub type PiEventHook {
  PiEventHook(
    event_name: String,   // e.g. "tool_call", "session_start"
    handler_body: String, // JS handler body as text (generated by Gleam, not hand-written)
  )
}

// -------------------------------------------------------------------
// PiParam helpers
// -------------------------------------------------------------------

pub fn string_param(name: String) -> PiParam {
  PiParam(name: name, param_type: "string", required: True)
}

pub fn opt_string_param(name: String) -> PiParam {
  PiParam(name: name, param_type: "string", required: False)
}

pub fn number_param(name: String) -> PiParam {
  PiParam(name: name, param_type: "number", required: True)
}

// -------------------------------------------------------------------
// FnArg helpers
// -------------------------------------------------------------------

pub fn lit(arg: String) -> FnArg {
  JsLiteral(arg)
}

pub fn from_param(expr: String) -> FnArg {
  FromParam(expr)
}

// -------------------------------------------------------------------
// ResultFormat helpers
// -------------------------------------------------------------------

pub fn raw_json() -> ResultFormat {
  RawJson
}

pub fn template(tpl: String) -> ResultFormat {
  Template(tpl)
}

pub fn custom_js(expr: String) -> ResultFormat {
  CustomJs(expr)
}

// -------------------------------------------------------------------
// PiToolCall → JS text
// These functions convert PiToolCall values into JavaScript source text
// -------------------------------------------------------------------

/// Generate the TypeBox parameters schema as JS text
pub fn params_to_js(params: List(PiParam)) -> String {
  case params {
    [] -> "{}"
    _ -> {
      let fields =
        params
        |> list.map(fn(p) {
          let base = case p.param_type {
            "string" -> "{ type: \"string\""
            "number" -> "{ type: \"number\""
            "boolean" -> "{ type: \"boolean\""
            _ -> "{ type: \"" <> p.param_type <> "\""
          }
          let closing = case p.required {
            True -> " }"
            False -> ", optional: true }"
          }
          "\"" <> p.name <> "\": " <> base <> closing
        })
        |> string.join(", ")
      "{ " <> fields <> " }"
    }
  }
}

/// Generate the function call arguments as JS text
pub fn args_to_js(args: List(FnArg)) -> String {
  args
  |> list.map(fn(a) {
    case a {
      JsLiteral(v) -> v
      FromParam(e) -> e
    }
  })
  |> string.join(", ")
}

/// Generate the result formatting JS text
pub fn result_to_js(format: ResultFormat) -> String {
  case format {
    RawJson -> "JSON.stringify(r.value)"
    Template(tpl) -> "`" <> tpl <> "`"
    CustomJs(expr) -> expr
  }
}

/// Generate the complete pi.registerTool({...}) block as JS text
pub fn to_js_text(tool: PiToolCall) -> String {
  let params_js = params_to_js(tool.params)
  let args_js = args_to_js(tool.args)
  let call_expr = tool.fn_name <> "(" <> args_js <> ")"
  let result_js = result_to_js(tool.result_format)

  [
    "  // " <> tool.description,
    "  pi.registerTool({",
    "    name: \"" <> tool.name <> "\",",
    "    description: \"" <> tool.description <> "\",",
    "    parameters: " <> params_js <> ",",
    "    async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {",
    "      try {",
    "        const result = await " <> call_expr <> ";",
    "        const r = unwrapGleamResult(result);",
    "        return r.ok ? { content: [{ type: \"text\", text: "
      <> result_js
      <> " }] } : { content: [{ type: \"text\", text: `Error: ${r.error}` }] };",
    "      } catch(e) { return { content: [{ type: \"text\", text: `Error: ${e.message}` }] }; }",
    "    }",
    "  });",
    "",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

/// Generate the import statement for this tool's Gleam module
/// The import path is relative to extension.js location.
/// extension.js lives at src/agent/extension/, so we go up to project root
/// then into the Gleam build output.
pub fn to_import_line(tool: PiToolCall) -> String {
  let base = "../../../build/dev/javascript/psypi/psypi"
  "import { " <> tool.fn_name <> " } from \"" <> base <> "/" <> tool.module <> ".mjs\";"
}

/// Generate the pi.on('event_name', handler) block as JS text
pub fn event_hook_to_js(hook: PiEventHook) -> String {
  [
    "  // Event hook: " <> hook.event_name,
    "  pi.on('" <> hook.event_name <> "', async (event, ctx) => {",
    hook.handler_body,
    "  });",
    "",
  ]
  |> list.map(fn(s) { s <> "\n" })
  |> string.concat
}

/// Helper to create an event hook
pub fn event_hook(name: String, handler_body: String) -> PiEventHook {
  PiEventHook(event_name: name, handler_body: handler_body)
}
